### ISSUE TITLE
kubesphere项目中的容器日志里面不能显示日志内容，而通过kubectl logs可以正常查看日志

### ISSUE THREAD

**Issue by jinmin527** [kubesphere/kubesphere#1017]
kubesphere项目中的容器日志里面不能显示日志内容，而通过kubectl logs可以正常查看日志

**Comment by huanggze** [comment]
请打印以下信息看看：
```
kubectl get po -n kubesphere-logging-system

kubectl logs -n kubesphere-logging-system <your_fluentbit_pod>
```

首次安装检查是否对容器日志路径设置了软连接，且没有修改 installer 安装时日志挂盘参数 #680

**Comment by jinmin527** [comment]
我是在已有的k8s集群上面用ks-installer进行安装的。没有修改过日志的路径。
kubectl logs -n kubesphere-logging-system fluent-bit-4zlj6 -c fluent-bit 

[2019/10/08 03:23:55] [ info] [storage] initializing...
[2019/10/08 03:23:55] [ info] [storage] in-memory
[2019/10/08 03:23:55] [ info] [storage] normal synchronization mode, checksum disabled
[2019/10/08 03:23:55] [ info] [engine] started (pid=15)
[2019/10/08 03:23:55] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2019/10/08 03:23:55] [ info] [filter_kube] local POD info OK
[2019/10/08 03:23:55] [ info] [filter_kube] testing connectivity with API server...
[2019/10/08 03:23:55] [ info] [filter_kube] API server connectivity OK

kubectl logs -n kubesphere-logging-system fluent-bit-4zlj6 -c config-reloader 
2019/10/08 03:23:55 Watching directory: "/fluent-bit/app-config/"

**Comment by huanggze** [comment]
目前看 fluent-bit 是好的。那可能是和 es 有关

UI 上有没有提示?

在终端下看看：
```
curl elasticsearch-logging-data.kubesphere-logging-system.svc:9200/_cat/indices
```

**Comment by jinmin527** [comment]
1.进入es对应的pod
kubectl exec -it -n kubesphere-logging-system elasticsearch-logging-data-0 bash
2.在其pod中执行
curl elasticsearch-logging-data.kubesphere-logging-system.svc:9200/_cat/indices

结果什么都没有

**Comment by jinmin527** [comment]
kubectl logs -n kubesphere-logging-system elasticsearch-logging-data-0

[2019-10-22T08:05:49,346][INFO ][o.e.p.PluginsService     ] [elasticsearch-logging-data-0] no plugins loaded
[2019-10-22T08:05:51,713][INFO ][o.e.d.DiscoveryModule    ] [elasticsearch-logging-data-0] using discovery type [zen] and host providers [settings]
[2019-10-22T08:05:52,143][INFO ][o.e.n.Node               ] [elasticsearch-logging-data-0] initialized
[2019-10-22T08:05:52,143][INFO ][o.e.n.Node               ] [elasticsearch-logging-data-0] starting ...
[2019-10-22T08:05:52,268][INFO ][o.e.t.TransportService   ] [elasticsearch-logging-data-0] publish_address {10.226.6.40:9300}, bound_addresses {0.0.0.0:9300}
[2019-10-22T08:05:52,277][INFO ][o.e.b.BootstrapChecks    ] [elasticsearch-logging-data-0] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2019-10-22T08:05:52,419][WARN ][o.e.d.z.UnicastZenPing   ] [elasticsearch-logging-data-0] failed to resolve host [elasticsearch-logging-discovery]
java.net.UnknownHostException: elasticsearch-logging-discovery: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:536) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:489) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:737) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$resolveHostsLists$0(UnicastZenPing.java:189) ~[elasticsearch-6.7.0.jar:6.7.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-6.7.0.jar:6.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[2019-10-22T08:05:55,428][WARN ][o.e.d.z.ZenDiscovery     ] [elasticsearch-logging-data-0] not enough master nodes discovered during pinging (found [[]], but needed [1]), pinging again
[2019-10-22T08:05:55,428][WARN ][o.e.d.z.UnicastZenPing   ] [elasticsearch-logging-data-0] failed to resolve host [elasticsearch-logging-discovery]
java.net.UnknownHostException: elasticsearch-logging-discovery
	at java.net.InetAddress$CachedAddresses.get(InetAddress.java:797) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:536) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:489) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:737) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$resolveHostsLists$0(UnicastZenPing.java:189) ~[elasticsearch-6.7.0.jar:6.7.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-6.7.0.jar:6.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[2019-10-22T08:05:58,430][WARN ][o.e.d.z.ZenDiscovery     ] [elasticsearch-logging-data-0] not enough master nodes discovered during pinging (found [[]], but needed [1]), pinging again
[2019-10-22T08:05:58,430][WARN ][o.e.d.z.UnicastZenPing   ] [elasticsearch-logging-data-0] failed to resolve host [elasticsearch-logging-discovery]

**Comment by huanggze** [comment]
es 没有报异常。那是怎么回事呢？

**Comment by jinmin527** [comment]
现在外部ES里面可以收集到数据了，但是页面显示日志的时候还是报错

**Comment by jinmin527** [comment]
问题解决了。一开始是docker日志有软链接，后面是ES版本太高，7.4的版本不行，换成6.7的就可以了
