### ISSUE TITLE
流水线测试，成功一次，之后未修改配置但执行异常

### ISSUE THREAD

**Issue by dpp814** [kubesphere/kubesphere#1237]
基于文档 快速入门 spring boot项目构建流水线
![image](https://user-images.githubusercontent.com/22487387/67666685-3f65c680-f9a7-11e9-96aa-ed430475926b.png)

异常信息：
Started by user dpp
Connecting to https://api.github.com using jenkinsfile-in-SCM/******
ERROR: Could not do lightweight checkout, falling back to heavyweight
java.net.ConnectException: Failed to connect to raw.githubusercontent.com/31.13.75.18:443
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:450)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:236)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.asStream(Requester.java:340)
	at org.kohsuke.github.GHContent.read(GHContent.java:117)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMFile.content(GitHubSCMFile.java:183)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Checking out git https://github.com/dpp814/devops-java-sample.git into /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script to read Jenkinsfile-online
using credential github-004885
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/dpp814/devops-java-sample.git
 >  init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:813)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:605)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1152)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Error performing command:  init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2049)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2010)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2006)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1638)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:811)
	... 9 more
Caused by: java.io.IOException: Cannot run program "" (in directory "/var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:935)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2038)
	... 13 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 18 more
ERROR: Error cloning remote repo 'origin'
Retrying after 10 seconds
using credential github-004885
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/dpp814/devops-java-sample.git
 >  init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:813)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:605)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1152)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Error performing command:  init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2049)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2010)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2006)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1638)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:811)
	... 9 more
Caused by: java.io.IOException: Cannot run program "" (in directory "/var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:935)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2038)
	... 13 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 18 more
ERROR: Error cloning remote repo 'origin'
Retrying after 10 seconds
using credential github-004885
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/dpp814/devops-java-sample.git
 >  init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:813)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:605)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1152)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Error performing command:  init /var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2049)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2010)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2006)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1638)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:811)
	... 9 more
Caused by: java.io.IOException: Cannot run program "" (in directory "/var/jenkins_home/workspace/2mDXAK_jenkinsfile-in-SCM_master@script"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:935)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2038)
	... 13 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 18 more
ERROR: Error cloning remote repo 'origin'

GitHub has been notified of this commit’s build result

ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE

**Comment by runzexia** [comment]
集群与github之间的网络情况如何？
网络情况不好的情况下，我们建议将仓库同步到国内地址进行执行

**Comment by dpp814** [comment]
服务器上能ping通，jenkins容器里面也能ping通，但是就是报连接超时；而且异常信息中不存在的目录也是有的：
![image](https://user-images.githubusercontent.com/22487387/67669413-c9fcf480-f9ac-11e9-8b3d-c3d2f48e99e2.png)
![image](https://user-images.githubusercontent.com/22487387/67669561-1c3e1580-f9ad-11e9-9cc7-bb07180fcdf1.png)
![image](https://user-images.githubusercontent.com/22487387/67669636-47c10000-f9ad-11e9-9149-fde35e467172.png)

**Comment by runzexia** [comment]
建议尝试下在环境里面进行 shallow clone 和 正常 clone

**Comment by dpp814** [comment]
服务器上面可以直接clone
![image](https://user-images.githubusercontent.com/22487387/67670410-ce2a1180-f9ae-11e9-9847-63e2dcaa73f2.png)

**Comment by runzexia** [comment]
shallow clone 试一下

**Comment by dpp814** [comment]
![image](https://user-images.githubusercontent.com/22487387/67671270-90c68380-f9b0-11e9-89d8-0ca65fbcfe52.png)
这样吗？ 50%之后就特别慢

**Comment by runzexia** [comment]
> ![image](https://user-images.githubusercontent.com/22487387/67671270-90c68380-f9b0-11e9-89d8-0ca65fbcfe52.png)
> 这样吗？ 50%之后就特别慢

是的，这可能和网络状态等有关系，上面的流水线失败原因我理解是clone失败导致的异常

**Comment by dpp814** [comment]
![image](https://user-images.githubusercontent.com/22487387/67671622-4265b480-f9b1-11e9-8d6b-88121ffbb59d.png)
正常来说 shallow应该比clone快吧，这边shallow clone完成后报错

**Comment by runzexia** [comment]
> ![image](https://user-images.githubusercontent.com/22487387/67671622-4265b480-f9b1-11e9-8d6b-88121ffbb59d.png)
> 正常来说 shallow应该比clone快吧，这边shallow clone完成后报错

是的因此kubesphere devops默认使用shallow clone

**Comment by dpp814** [comment]
是不是 某个代理的

**Comment by runzexia** [comment]
建议再尝试一下，如果clone之后仍然报错可以联系github提交工单
/close
