### ISSUE TITLE
gitee构建流水线，未找到 Pipeline 配置文件

### ISSUE THREAD

**Issue by dpp814** [kubesphere/kubesphere#1260]
![image](https://user-images.githubusercontent.com/22487387/67822488-8238b300-fafb-11e9-9f83-60dc3cb7157d.png)
错误日志：
Started by user dpp
[Wed Oct 30 01:56:01 UTC 2019] Starting branch indexing...
 >  --version # timeout=10
 >  --version # timeout=10
using GIT_ASKPASS to set credentials 
 >  ls-remote https://gitee.com/dpp814/devops-java-sample.git # timeout=10
ERROR: [Wed Oct 30 01:56:01 UTC 2019] Could not update folder level actions from source project-lLWzED2mDXAKdevops-gitee
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Caused: java.io.IOException: Cannot run program "": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:935)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2038)
Caused: hudson.plugins.git.GitException: Error performing command:  ls-remote https://gitee.com/dpp814/devops-java-sample.git
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2049)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1666)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1657)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getRemoteReferences(CliGitAPIImpl.java:2877)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieveActions(AbstractGitSCMSource.java:1113)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:764)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:591)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1025)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[Wed Oct 30 01:56:01 UTC 2019] Finished branch indexing. Indexing took 18 ms
FATAL: Failed to recompute children of project-lLWzED2mDXAK » devops-gitee
hudson.plugins.git.GitException: Error performing command:  ls-remote https://gitee.com/dpp814/devops-java-sample.git
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2049)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1666)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1657)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getRemoteReferences(CliGitAPIImpl.java:2877)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieveActions(AbstractGitSCMSource.java:1113)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:764)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:591)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1025)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: java.io.IOException: Cannot run program "": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:935)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2038)
	... 12 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 17 more
Finished: FAILURE

**Comment by runzexia** [comment]
确认一下。
jenkins 有做过配置调整吗？

**Comment by dpp814** [comment]
就加了maven插件 其他没动过

**Comment by runzexia** [comment]
发一下远程信息到 kubesphere@yunify.com

**Comment by dpp814** [comment]
已经发了，还麻烦远程看看

**Comment by runzexia** [comment]
![image](https://user-images.githubusercontent.com/31230341/67827624-7fde5500-fb0b-11e9-8964-83810edf1d73.png)
经检查是用户配置全局工具安装时，覆盖了默认git client的设置，导致找不到git命令行
