### ISSUE TITLE
openpitrix-iam-service组件异常,不能启动

### ISSUE THREAD

**Issue by Wandering** [kubesphere/kubesphere#1359]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
openpitrix-iam-service组件启动不起来
容器内错误日志:
```
2019-11-05 14:34:03.817: /go/src/openpitrix.io/openpitrix/pkg/models/user.go:18 +0x36

2019-11-05 14:34:03.817: /go/src/openpitrix.io/openpitrix/pkg/util/idutil/id.go:54 +0x29

2019-11-05 14:34:03.817: created by openpitrix.io/openpitrix/pkg/service/iam.Serve

2019-11-05 14:34:03.817: openpitrix.io/openpitrix/pkg/service/iam.initIAMAccount()

2019-11-05 14:34:03.817: /go/src/openpitrix.io/openpitrix/pkg/util/idutil/id.go:45 +0x2d

2019-11-05 14:34:03.817: openpitrix.io/openpitrix/pkg/util/idutil.GetUuid(0xc5502b, 0x4, 0x0, 0x3c)

2019-11-05 14:34:03.817: openpitrix.io/openpitrix/pkg/models.NewUserId(0xc000064700, 0x0)

2019-11-05 14:34:03.817: openpitrix.io/openpitrix/pkg/models.NewUser(0xc000038077, 0x5, 0xc000400480, 0x3c, 0xc000038077, 0xc, 0xc5bab9, 0xc, 0x0, 0x0, ...)

2019-11-05 14:34:03.817: /go/src/openpitrix.io/openpitrix/pkg/models/user.go:39 +0x26

2019-11-05 14:34:03.817: /go/src/openpitrix.io/openpitrix/pkg/service/iam/init.go:61 +0x3dc

2019-11-05 14:34:03.817: /go/src/openpitrix.io/openpitrix/pkg/service/iam/server.go:25 +0x5f

2019-11-05 14:34:03.816: panic: runtime error: invalid memory address or nil pointer dereference

2019-11-05 14:34:03.816:

2019-11-05 14:34:03.816: /go/src/openpitrix.io/openpitrix/vendor/github.com/sony/sonyflake/sonyflake.go:89 +0x37

2019-11-05 14:34:03.816: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x94ceb7]

2019-11-05 14:34:03.816: goroutine 66 [running]:

2019-11-05 14:34:03.816: openpitrix.io/openpitrix/pkg/util/idutil.GetIntId(0xc0003fe000)
```
容器信息:
```
Name:               openpitrix-iam-service-deployment-768555b66d-tf7fd
Namespace:          openpitrix-system
Priority:           0
PriorityClassName:  <none>
Node:               node4/10.0.0.224
Start Time:         Tue, 05 Nov 2019 01:15:16 -0500
Labels:             app=openpitrix
                    component=openpitrix-iam-service
                    pod-template-hash=768555b66d
                    version=v0.3.5
Annotations:        cni.projectcalico.org/podIP: 100.127.10.67/32
Status:             Running
IP:                 100.127.10.67
Controlled By:      ReplicaSet/openpitrix-iam-service-deployment-768555b66d
Init Containers:
  wait-mysql:
    Container ID:  docker://f1c775947641633239292ecd7a9e0e919f557a0b90926479e5643f5e2f388396
    Image:         busybox:1.28.4
    Image ID:      docker-pullable://busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until nc -z openpitrix-db.openpitrix-system.svc 3306; do echo "waiting for mysql"; sleep 2; done;
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 05 Nov 2019 01:15:18 -0500
      Finished:     Tue, 05 Nov 2019 01:18:06 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qz8zj (ro)
  wait-etcd:
    Container ID:  docker://ef062c4bd78adf7f443e2a7afe3246dd616de98a433ecfc70c9b0ffaad4584d2
    Image:         busybox:1.28.4
    Image ID:      docker-pullable://busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until nc -z openpitrix-etcd.openpitrix-system.svc 2379; do echo "waiting for etcd"; sleep 2; done;
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 05 Nov 2019 01:18:07 -0500
      Finished:     Tue, 05 Nov 2019 01:18:07 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qz8zj (ro)
Containers:
  openpitrix-iam-service:
    Container ID:  docker://ef82d26d656ca7ce439a23cda18dec0bb7ce02a2effafaf3734e9f54032536f0
    Image:         openpitrix/openpitrix:v0.3.5
    Image ID:      docker-pullable://openpitrix/openpitrix@sha256:e512de5070f122310e144d666629f8c7f2f4807bc0e043a28f6d5135d584546b
    Port:          9115/TCP
    Host Port:     0/TCP
    Command:
      iam-service
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 05 Nov 2019 01:28:55 -0500
      Finished:     Tue, 05 Nov 2019 01:28:55 -0500
    Ready:          False
    Restart Count:  7
    Limits:
      cpu:     500m
      memory:  500Mi
    Requests:
      cpu:     50m
      memory:  100Mi
    Environment:
      OPENPITRIX_GRPC_SHOW_ERROR_CAUSE:  true
      OPENPITRIX_LOG_LEVEL:              ${OPENPITRIX_LOG_LEVEL}
      OPENPITRIX_MYSQL_DATABASE:         iam
      OPENPITRIX_MYSQL_PASSWORD:         <set to the key 'password.txt' in secret 'mysql-pass'>        Optional: false
      OPENPITRIX_IAM_SECRET_KEY:         <set to the key 'secret-key.txt' in secret 'iam-secret-key'>  Optional: false
      IAM_INIT_CLIENT_ID:                <set to the key 'client-id.txt' in secret 'iam-client'>       Optional: false
      IAM_INIT_CLIENT_SECRET:            <set to the key 'client-secret.txt' in secret 'iam-client'>   Optional: false
      IAM_INIT_ACCOUNT_EMAIL:            admin@op.com
      IAM_INIT_ACCOUNT_PASSWORD:         <set to the key 'admin-password.txt' in secret 'iam-account'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qz8zj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-qz8zj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-qz8zj
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned openpitrix-system/openpitrix-iam-service-deployment-768555b66d-tf7fd to node4
  Normal   Pulled     18m                   kubelet, node4     Container image "busybox:1.28.4" already present on machine
  Normal   Created    18m                   kubelet, node4     Created container wait-mysql
  Normal   Started    18m                   kubelet, node4     Started container wait-mysql
  Normal   Pulled     15m                   kubelet, node4     Container image "busybox:1.28.4" already present on machine
  Normal   Created    15m                   kubelet, node4     Created container wait-etcd
  Normal   Started    15m                   kubelet, node4     Started container wait-etcd
  Normal   Pulled     14m (x4 over 15m)     kubelet, node4     Container image "openpitrix/openpitrix:v0.3.5" already present on machine
  Normal   Created    14m (x4 over 15m)     kubelet, node4     Created container openpitrix-iam-service
  Normal   Started    14m (x4 over 15m)     kubelet, node4     Started container openpitrix-iam-service
  Warning  BackOff    3m15s (x57 over 15m)  kubelet, node4     Back-off restarting failed container

```

**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
运行在虚拟机上。
系统配置6台 8c16G主机Centos7
**错误信息或截图**

**Installer版本**
2.0.2

**Comment by wansir** [comment]
https://github.com/kubesphere/ks-installer/issues/17#issuecomment-522401975

这个问题会在 2.1.0 版本中修复

**Comment by Wandering** [comment]
问题已解决非常感谢
