### ISSUE TITLE
添加应用仓库报错

### ISSUE THREAD

**Issue by Wandering** [kubesphere/kubesphere#1363]
使用版本 2.0.2
报错:
```
[{"@type":"type.googleapis.com/openpitrix.ErrorDetail","error_name":"internal_error","cause":"runtime error: invalid memory address or nil pointer dereference"}]
```
xiang'guan相关截图
![image](https://user-images.githubusercontent.com/11769582/68193115-76faf100-ffed-11e9-9ea5-7b81dd5c8212.png)

相关错误信息:
```
2019-11-05 08:57:49.88771 -ERROR- err: runtime error: invalid memory address or nil pointer dereference, errMsg: 内部错误 (grpc_server.go:117)
2019-11-05 08:57:49.88807 -INFO- Handled request [CreateRepo] [&{UserId:system Role:global_admin}] exec_time is [9.573839132s] (grpc_server.go:177)(78bc1140-692c-4405-9bd6-2a56a9e8da9a)
2019-11-05 08:57:49.98278 -INFO- Request received [DescribeRepos] [&{UserId:system Role:global_admin}] [{"status":["active"],"controller":0}] (grpc_server.go:169)(3460aa21-2112-4ad9-9acc-1535878976d5)
2019-11-05 08:57:49.9879  -INFO- Handled request [DescribeRepos] [&{UserId:system Role:global_admin}] exec_time is [4.985726ms] (grpc_server.go:177)(3460aa21-2112-4ad9-9acc-1535878976d5)
2019-11-05 08:58:36.81256 -INFO- Request received [DescribeRepos] [&{UserId:system Role:global_admin}] [{"status":["active"],"controller":0}] (grpc_server.go:169)(c7371458-f8ee-4e1d-843e-be971874be6c)
2019-11-05 08:58:36.82702 -INFO- Handled request [DescribeRepos] [&{UserId:system Role:global_admin}] exec_time is [14.283478ms] (grpc_server.go:177)(c7371458-f8ee-4e1d-843e-be971874be6c)
2019-11-05 08:59:07.01155 -INFO- Request received [CreateRepo] [&{UserId:system Role:global_admin}] [{"name":"微软的chart仓库","type":"http","url":"http://mirror.azure.cn/kubernetes/charts/","credential":"{}","visibility":"public","providers":["kubernetes"],"app_default_status":"active"}] (grpc_server.go:169)(69e33d02-2ba5-4099-97f9-2ec88fe8deb2)
2019-11-05 08:59:17.47715 -CRITICAL- GRPC server recovery with error: runtime error: invalid memory address or nil pointer dereference (grpc_server.go:114)
2019-11-05 08:59:17.4783  -CRITICAL- goroutine 533 [running]:\nruntime/debug.Stack(0x0, 0x0, 0x218fac9)\n	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\nopenpitrix.io/openpitrix/pkg/manager.(*GrpcServer).Serve.func4(0x1d8fd20, 0x3e2f8b0, 0x199, 0x0)\n	/go/src/openpitrix.io/openpitrix/pkg/manager/grpc_server.go:115 +0x9c\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x1d8fd20, 0x3e2f8b0, 0x220fb58, 0x0, 0xc005cc4015)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/recovery/interceptors.go:47 +0x43\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0xc00000c160, 0xc00405d628)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/recovery/interceptors.go:21 +0x5f\npanic(0x1d8fd20, 0x3e2f8b0)\n	/usr/local/go/src/runtime/panic.go:513 +0x1b9\nopenpitrix.io/openpitrix/vendor/github.com/sony/sonyflake.(*Sonyflake).NextID(0x0, 0x0, 0x0, 0x0)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/sony/sonyflake/sonyflake.go:89 +0x37\nopenpitrix.io/openpitrix/pkg/util/idutil.GetIntId(0x1e73bc0)\n	/go/src/openpitrix.io/openpitrix/pkg/util/idutil/id.go:45 +0x2d\nopenpitrix.io/openpitrix/pkg/util/idutil.GetUuid(0x215704a, 0x5, 0x0, 0x0)\n	/go/src/openpitrix.io/openpitrix/pkg/util/idutil/id.go:54 +0x29\nopenpitrix.io/openpitrix/pkg/models.NewRepoId(0xc00405d350, 0x90c6cf)\n	/go/src/openpitrix.io/openpitrix/pkg/models/repo.go:18 +0x36\nopenpitrix.io/openpitrix/pkg/models.NewRepo(0xc00124e2a0, 0x14, 0x0, 0x0, 0xc001254608, 0x4, 0xc001256240, 0x29, 0xc00125460c, 0x2, ...)\n	/go/src/openpitrix.io/openpitrix/pkg/models/repo.go:43 +0x26\nopenpitrix.io/openpitrix/pkg/service/repo.(*Server).CreateRepo(0x3e7db30, 0x23f4b80, 0xc001252e70, 0xc00074a900, 0x3e7db30, 0xc000d4c140, 0x0)\n	/go/src/openpitrix.io/openpitrix/pkg/service/repo/handler.go:122 +0x2cf\nopenpitrix.io/openpitrix/pkg/pb._RepoManager_CreateRepo_Handler.func1(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0xc00125f588, 0x42b072, 0xc000d4c170, 0xc00125f5a8)\n	/go/src/openpitrix.io/openpitrix/pkg/pb/repo.pb.go:1231 +0x86\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0x0, 0x200, 0xc0061f0780, 0xc00122dce0)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x104\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0xc00122d800, 0xc000594640, 0x0, 0x0, 0x0, 0x0)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/recovery/interceptors.go:25 +0x97\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0x205c500, 0xc00074a900, 0xa, 0x215ecf9)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x97\nopenpitrix.io/openpitrix/pkg/manager.(*GrpcServer).Serve.func3(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0xc00122d800, 0xc000594640, 0x205c500, 0xc00074a900, 0x0, 0x0)\n	/go/src/openpitrix.io/openpitrix/pkg/manager/grpc_server.go:110 +0x5f\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0x0, 0x0, 0x20, 0xc00125f910)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x97\nopenpitrix.io/openpitrix/pkg/manager.(*GrpcServer).Serve.func2(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0xc00122d800, 0xc000594640, 0x48d356, 0x5dc139db, 0xb28957, 0x8c7f5642b01)\n	/go/src/openpitrix.io/openpitrix/pkg/manager/grpc_server.go:104 +0x5f\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0xc00125f910, 0x3, 0x3, 0xc000d520a0)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x97\nopenpitrix.io/openpitrix/pkg/manager.(*GrpcServer).unaryServerLogInterceptor.func1(0x23f4b80, 0xc001252e70, 0x205c500, 0xc00074a900, 0xc00122d800, 0xc000594640, 0x1dc54e0, 0x205c500, 0x7f90e07bed01, 0x0)\n	/go/src/openpitrix.io/openpitrix/pkg/manager/grpc_server.go:174 +0x1f4\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x23f4b80, 0xc001252c30, 0x205c500, 0xc00074a900, 0x0, 0x1fd5e00, 0x1, 0xc000594640)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x97\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/validator.UnaryServerInterceptor.func1(0x23f4b80, 0xc001252c30, 0x205c500, 0xc00074a900, 0xc00122d800, 0xc000594640, 0x1d8eca0, 0x3e7db30, 0xc002d73aa0, 0x40c548)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/validator/validator.go:26 +0x8a\nopenpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x23f4b80, 0xc001252c30, 0x205c500, 0xc00074a900, 0xc00122d800, 0xc00122d820, 0x1d8eca0, 0x3e7db30, 0x20894c0, 0xc000c9c400)\n	/go/src/openpitrix.io/openpitrix/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:37 +0x153\nopenpitrix.io/openpitrix/pkg/pb._RepoManager_CreateRepo_Handler(0x2042900, 0x3e7db30, 0x23f4b80, 0xc001252c30, 0xc0003322a0, 0xc000b0a390, 0x0, 0x0, 0x0, 0x497872)\n	/go/src/openpitrix.io/openpitrix/pkg/pb/repo.pb.go:1233 +0x158\nopenpitrix.io/openpitrix/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000846000, 0x240a020, 0xc0009fe000, 0xc000c9c400, 0xc000d460f0, 0x3e3c5c0, 0x0, 0x0, 0x0)\n	/go/src/openpitrix.io/openpitrix/vendor/google.golang.org/grpc/server.go:1020 +0x4cd\nopenpitrix.io/openpitrix/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000846000, 0x240a020, 0xc0009fe000, 0xc000c9c400, 0x0)\n	/go/src/openpitrix.io/openpitrix/vendor/google.golang.org/grpc/server.go:1258 +0x1308\nopenpitrix.io/openpitrix/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000b7e020, 0xc000846000, 0x240a020, 0xc0009fe000, 0xc000c9c400)\n	/go/src/openpitrix.io/openpitrix/vendor/google.golang.org/grpc/server.go:689 +0x9f\ncreated by openpitrix.io/openpitrix/vendor/google.golang.org/grpc.(*Server).serveStreams.func1\n	/go/src/openpitrix.io/openpitrix/vendor/google.golang.org/grpc/server.go:687 +0xa1\n (grpc_server.go:115)
2019-11-05 08:59:17.47856 -ERROR- err: runtime error: invalid memory address or nil pointer dereference, errMsg: 内部错误 (grpc_server.go:117)
2019-11-05 08:59:17.47894 -INFO- Handled request [CreateRepo] [&{UserId:system Role:global_admin}] exec_time is [10.467188555s] (grpc_server.go:177)(69e33d02-2ba5-4099-97f9-2ec88fe8deb2)
2019-11-05 08:59:17.63543 -INFO- Request received [DescribeRepos] [&{UserId:system Role:global_admin}] [{"status":["active"],"controller":0}] (grpc_server.go:169)(0cae54d6-2a51-4a3b-aced-15e91865faec)
2019-11-05 08:59:17.6418  -INFO- Handled request [DescribeRepos] [&{UserId:system Role:global_admin}] exec_time is [6.245708ms] (grpc_server.go:177)(0cae54d6-2a51-4a3b-aced-15e91865faec)
```

**Comment by Wandering** [comment]
其中补充下  helm version:2.14.3

**Comment by zheng1** [comment]
你好, 如果pod的ip不是一个标准的内网ip, 如 192.168/16 或者 10/8 或者 172.16/12 的话, 需要给所有openpitrix的Deployment加上env OPENPITRIX_ID_RANDOM_SEED=yes

**Comment by Wandering** [comment]
问题已解决,非常感谢

**Comment by Wandering** [comment]
[{"@type":"type.googleapis.com/openpitrix.ErrorDetail","error_name":"create_resources_failed","cause":"repo [repo-Xo2K70RzjQ9p] had running index event"}] @zheng1 但是在点同步的时候又出现了新的问题

**Comment by Wandering** [comment]
应用仓库中的应用可用,但是会有一些问题,某些打开的时候回抛出如下异常

![image](https://user-images.githubusercontent.com/11769582/68196910-3fdc0e00-fff4-11e9-93e0-ed5e30c90572.png)

**Comment by zheng1** [comment]
Fixed in 2.1
