### ISSUE TITLE
安装显示成功，但是登录失败，显示 Internal Server Error

### ISSUE THREAD

**Issue by limpo1989** [kubesphere/kubesphere#1495]
**问题描述**
使用官网最新的AllInOne-v2.1.0版本进行安装，安装之后显示成功，但是登录失败提示 Internal Server Error

**安装环境的硬件配置**
CentOS Linux release 7.5.1804 (Core)
Hyper-V  虚拟机安装全新环境，连接外网
8核心，13G内存

**错误信息或截图**

```
[root@ks-allinone admin]# kubectl get pod --all-namespaces            
NAMESPACE                      NAME                                           READY   STATUS     RESTARTS   AGE
kube-system                    calico-kube-controllers-68499cf5f-hnnn9        1/1     Running    0          28m
kube-system                    calico-node-hvbjj                              1/1     Running    0          28m
kube-system                    coredns-647d4f64c4-qk75g                       1/1     Running    0          28m
kube-system                    dns-autoscaler-77486c4479-rp794                1/1     Running    0          28m
kube-system                    kube-apiserver-ks-allinone                     1/1     Running    0          28m
kube-system                    kube-controller-manager-ks-allinone            1/1     Running    0          28m
kube-system                    kube-proxy-dxlzg                               1/1     Running    0          29m
kube-system                    kube-scheduler-ks-allinone                     1/1     Running    0          28m
kube-system                    nodelocaldns-d27jh                             1/1     Running    0          28m
kube-system                    openebs-localpv-provisioner-7b55587dbd-bhq8w   1/1     Running    0          27m
kube-system                    openebs-ndm-bh8h4                              1/1     Running    0          27m
kube-system                    openebs-ndm-operator-69cbc86975-475jk          1/1     Running    1          27m
kube-system                    tiller-deploy-55fc49c595-m56vs                 1/1     Running    0          28m
kubesphere-controls-system     default-http-backend-6555ff6898-grz5n          1/1     Running    0          25m
kubesphere-monitoring-system   kube-state-metrics-868fcf6b48-4lqv2            4/4     Running    0          24m
kubesphere-monitoring-system   node-exporter-nrzj2                            2/2     Running    0          24m
kubesphere-monitoring-system   prometheus-k8s-0                               3/3     Running    1          24m
kubesphere-monitoring-system   prometheus-k8s-system-0                        3/3     Running    1          24m
kubesphere-monitoring-system   prometheus-operator-685bc484cb-fg72q           1/1     Running    0          24m
kubesphere-system              ks-account-d4c5cdf9d-qp84m                     0/1     Init:0/2   0          25m
kubesphere-system              ks-apigateway-65dd54f989-9g499                 1/1     Running    0          25m
kubesphere-system              ks-apiserver-6d7ddd7d-tttkn                    1/1     Running    0          25m
kubesphere-system              ks-console-6f7f75bb48-ltjcv                    1/1     Running    0          25m
kubesphere-system              ks-controller-manager-6dd9b76d75-jrqrm         1/1     Running    0          25m
kubesphere-system              ks-installer-7987c659d6-qbz8r                  1/1     Running    0          27m
kubesphere-system              openldap-0                                     1/1     Running    0          26m
kubesphere-system              redis-5d4844b947-fgjmx                         1/1     Running    0          26m
```

```
[root@ks-allinone admin]# docker logs 98cd940c0cfe
> kubesphere-console@2.1.0 serve /root/KubeSphereUI
> NODE_ENV=production node server/server.js

Dashboard app running at port 8000
  <-- GET / 2019/11/13T11:17:23.625
ERR { UnauthorizedError: Not Login
    at Object.throw (/root/KubeSphereUI/server/server.js:164:1927)
    at getCurrentUser (/root/KubeSphereUI/server/server.js:131:50325)
    at renderView (/root/KubeSphereUI/server/server.js:131:50957)
    at i (/root/KubeSphereUI/server/server.js:31:1844)
    at /root/KubeSphereUI/server/server.js:31:1866
    at /root/KubeSphereUI/server/server.js:296:4171
    at i (/root/KubeSphereUI/server/server.js:31:1844)
    at /root/KubeSphereUI/server/server.js:31:1866
    at /root/KubeSphereUI/server/server.js:352:1378
    at i (/root/KubeSphereUI/server/server.js:31:1844)
    at /root/KubeSphereUI/server/server.js:31:1866
    at /root/KubeSphereUI/server/server.js:296:4171
    at i (/root/KubeSphereUI/server/server.js:31:1844)
    at /root/KubeSphereUI/server/server.js:31:1866
    at /root/KubeSphereUI/server/server.js:352:1378
    at i (/root/KubeSphereUI/server/server.js:31:1844) message: 'Not Login' }
  --> GET / 302 10ms 43b 2019/11/13T11:17:23.634
  <-- GET /login 2019/11/13T11:17:28.040
  --> GET /login 200 12ms 15.97kb 2019/11/13T11:17:28.052
  <-- POST /login 2019/11/13T11:19:21.301
  --> POST /login 200 11ms 16.15kb 2019/11/13T11:19:21.312
  <-- GET /login 2019/11/13T11:20:04.419
  --> GET /login 200 76ms 15.97kb 2019/11/13T11:20:04.495
  <-- POST /login 2019/11/13T11:20:29.339
ERR { code: 502, statusText: 'Bad Gateway', message: '502 Bad Gateway\n' }
  --> POST /login 200 1,025ms 16.15kb 2019/11/13T11:20:30.364
```
**Installer版本**
kubesphere-all-v2.1.0

**Comment by zryfish** [comment]
`kubesphere-system              ks-account-d4c5cdf9d-qp84m                     0/1     Init:0/2   0          25m`
还有pod没有起来，等所有pod起来

**Comment by limpo1989** [comment]
@zryfish 等一个小时都起不来，重新卸载安装也是一样

**Comment by zryfish** [comment]
你看下那个 Init 的 pod 日记，看下 https://github.com/kubesphere/ks-installer/issues/33 这个issue

**Comment by limpo1989** [comment]
@zryfish 
```
[root@ks-allinone admin]# kubectl logs -n kubesphere-system ks-account-d4c5cdf9d-t9h5j
Error from server (BadRequest): container "ks-account" in pod "ks-account-d4c5cdf9d-t9h5j" is waiting to start: PodInitializing

[root@ks-allinone admin]# cat /etc/resolv.conf 
# Generated by NetworkManager
nameserver 114.114.114.114
nameserver 8.8.8.8
```

**Comment by limpo1989** [comment]
等待一晚上仍然没有启动
```
[root@ks-allinone admin]# kubectl get pod --all-namespaces 
NAMESPACE                      NAME                                           READY   STATUS     RESTARTS   AGE
kube-system                    calico-kube-controllers-68499cf5f-mck5z        1/1     Running    1          153m
kube-system                    calico-node-mrtpw                              1/1     Running    1          153m
kube-system                    coredns-647d4f64c4-2wdmf                       1/1     Running    1          153m
kube-system                    dns-autoscaler-77486c4479-nlhvh                1/1     Running    1          153m
kube-system                    kube-apiserver-ks-allinone                     1/1     Running    1          153m
kube-system                    kube-controller-manager-ks-allinone            1/1     Running    1          153m
kube-system                    kube-proxy-c5knv                               1/1     Running    1          154m
kube-system                    kube-scheduler-ks-allinone                     1/1     Running    1          153m
kube-system                    nodelocaldns-fvnfw                             1/1     Running    1          153m
kube-system                    openebs-localpv-provisioner-7b55587dbd-r79fv   1/1     Running    1          151m
kube-system                    openebs-ndm-44cs9                              1/1     Running    1          151m
kube-system                    openebs-ndm-operator-69cbc86975-ghldg          1/1     Running    2          151m
kube-system                    tiller-deploy-55fc49c595-cddmd                 1/1     Running    1          152m
kubesphere-controls-system     default-http-backend-6555ff6898-csgnz          1/1     Running    1          149m
kubesphere-monitoring-system   kube-state-metrics-868fcf6b48-fwx8h            4/4     Running    4          147m
kubesphere-monitoring-system   node-exporter-ztg6f                            2/2     Running    2          148m
kubesphere-monitoring-system   prometheus-k8s-0                               3/3     Running    4          148m
kubesphere-monitoring-system   prometheus-k8s-system-0                        3/3     Running    4          148m
kubesphere-monitoring-system   prometheus-operator-685bc484cb-p8r9n           1/1     Running    1          148m
kubesphere-system              ks-account-d4c5cdf9d-xwxwc                     0/1     Init:0/2   0          133m
kubesphere-system              ks-apigateway-65dd54f989-5nwjl                 1/1     Running    0          133m
kubesphere-system              ks-apiserver-6d7ddd7d-dxzrg                    1/1     Running    0          133m
kubesphere-system              ks-console-6f7f75bb48-qrn66                    1/1     Running    0          133m
kubesphere-system              ks-controller-manager-6dd9b76d75-cz2sk         1/1     Running    0          133m
kubesphere-system              ks-installer-7987c659d6-2kf9d                  1/1     Running    1          151m
kubesphere-system              openldap-0                                     1/1     Running    1          150m
kubesphere-system              redis-5d4844b947-rn4sb                         1/1     Running    1          150m
```

```
[root@ks-allinone admin]# kubectl describe -n kubesphere-system ks-account-d4c5cdf9d-xwxwc
error: the server doesn't have a resource type "ks-account-d4c5cdf9d-xwxwc"
[root@ks-allinone admin]# kubectl describe -n kubesphere-system pod ks-account-d4c5cdf9d-xwxwc
Name:           ks-account-d4c5cdf9d-xwxwc
Namespace:      kubesphere-system
Priority:       0
Node:           ks-allinone/192.168.212.211
Start Time:     Wed, 13 Nov 2019 20:54:45 +0800
Labels:         app=ks-account
                pod-template-hash=d4c5cdf9d
                tier=backend
                version=v2.1.0
Annotations:    <none>
Status:         Pending
IP:             10.233.99.46
Controlled By:  ReplicaSet/ks-account-d4c5cdf9d
Init Containers:
  wait-redis:
    Container ID:  docker://fe8a113e36d30602110dd2676907bac27ac5361e9c31a1d78427022819f21046
    Image:         busybox:1.28.4
    Image ID:      docker-pullable://busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until nc -z redis.kubesphere-system.svc 6379; do echo "waiting for redis"; sleep 2; done;
    State:          Running
      Started:      Wed, 13 Nov 2019 20:54:50 +0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kubesphere-token-pkf68 (ro)
  wait-ldap:
    Container ID:  
    Image:         busybox:1.28.4
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until nc -z openldap.kubesphere-system.svc 389; do echo "waiting for ldap"; sleep 2; done;
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kubesphere-token-pkf68 (ro)
Containers:
  ks-account:
    Container ID:  
    Image:         kubesphere/ks-account:v2.1.0
    Image ID:      
    Port:          9090/TCP
    Host Port:     0/TCP
    Command:
      ks-iam
      --logtostderr=true
      --jwt-secret=$(JWT_SECRET)
      --admin-password=$(ADMIN_PASSWORD)
      --enable-multi-login=False
      --token-idle-timeout=40m
      --redis-url=redis://redis.kubesphere-system.svc:6379
      --generate-kubeconfig=False
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  500Mi
    Requests:
      cpu:     20m
      memory:  100Mi
    Environment:
      KUBECTL_IMAGE:   kubesphere/kubectl:v1.0.0
      JWT_SECRET:      <set to the key 'jwt-secret' in secret 'ks-account-secret'>      Optional: false
      ADMIN_PASSWORD:  <set to the key 'admin-password' in secret 'ks-account-secret'>  Optional: false
    Mounts:
      /etc/ks-iam from user-init (rw)
      /etc/kubesphere from kubesphere-config (rw)
      /etc/kubesphere/rules from policy-rules (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubesphere-token-pkf68 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  policy-rules:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      policy-rules
    Optional:  false
  user-init:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      user-init
    Optional:  false
  kubesphere-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubesphere-config
    Optional:  false
  kubesphere-token-pkf68:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubesphere-token-pkf68
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 60s
                 node.kubernetes.io/unreachable:NoExecute for 60s
Events:          <none>
```

**Comment by limpo1989** [comment]
重启机器后事件提示错误，请问是什么原因呢 @zryfish 
```
[root@ks-allinone admin]# kubectl describe -n kubesphere-system pod ks-account-d4c5cdf9d-txln4

...

Events:
  Type     Reason            Age                From                  Message
  ----     ------            ----               ----                  -------
  Warning  FailedScheduling  20m (x2 over 20m)  default-scheduler     0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules.
  Normal   Scheduled         20m                default-scheduler     Successfully assigned kubesphere-system/ks-account-d4c5cdf9d-txln4 to ks-allinone
  Normal   Pulled            20m                kubelet, ks-allinone  Container image "busybox:1.28.4" already present on machine
  Normal   Created           20m                kubelet, ks-allinone  Created container wait-redis
  Normal   Started           20m                kubelet, ks-allinone  Started container wait-redis
```

**Comment by zryfish** [comment]
`kubectl -n kubesphere-system exec -ti ks-account-d4c5cdf9d-xwxwc nslookup redis.kubesphere-system.svc`
你执行这个命令看下，这个原因是ks-account 这个 pod 无法解析 redis 这个 svc

**Comment by limpo1989** [comment]
这个容器没有运行起来 我换了一个别的执行了 @zryfish 
```
[root@ks-allinone kubesphere-all-v2.1.0]# kubectl -n kubesphere-system exec -ti ks-account-d4c5cdf9d-txln4 nslookup redis.kubesphere-system.svc
error: unable to upgrade connection: container not found ("ks-account")

[root@ks-allinone kubesphere-all-v2.1.0]# kubectl -n kubesphere-system exec -ti ks-apigateway-65dd54f989-7g8w6 nslookup redis.kubesphere-system.svc                          
nslookup: can't resolve '(null)': Name does not resolve

Name:      redis.kubesphere-system.svc
Address 1: 10.233.45.8 redis.kubesphere-system.svc.cluster.local
```

**Comment by limpo1989** [comment]
使用 upgrade.sh 升级之后 可以成功进入了，但是多出来的openpitrix 是Init状态，重启机器之后又和原来一个样子了 ks-account pod起不来了 重新执行upgrade.sh 也不行

**Comment by BlueSky-YJS** [comment]
# /usr/local/bin/kubectl logs ks-apigateway-57594c7b96-kzq5h -n kubesphere-system
2020/06/15 03:24:54 [INFO][cache:0xc000859130] Started certificate maintenance routine
[DEV NOTICE] Registered directive 'authenticate' before 'jwt'
[DEV NOTICE] Registered directive 'authentication' before 'jwt'
[DEV NOTICE] Registered directive 'swagger' before 'jwt'
Activating privacy features... done.
E0615 03:24:59.290107       1 redis.go:51] unable to reach redis hostdial tcp: i/o timeout
2020/06/15 03:24:59 dial tcp: i/o timeout
查看这个ks-apigateway-57594c7b96-kzq5h日志是报这个错误，导致ks-account pod起不来，登录也是会爆Internal Server Error  不知道这个到底应该怎么调整呢？
