### ISSUE TITLE
可能由ks-apiserver引起的界面超时

### ISSUE THREAD

**Issue by k0ngk0ng** [kubesphere/kubesphere#1560]
KubeSphere: 2.1.0
目前无法复现
出问题时，查看监控中心的页面会比较明显效果（请求多，部分图表一直loading）

排查经过：
1. 查看 kubesphere-controls-system 的 kubesphere-router-kubesphere-system 日志
发现大量的 timed out  （我们把 ks-console加入了 ingress），所有 timed out 日志都指向一个 ks-console实例
```
2019/11/21 08:00:30 [error] 57#57: *57714962 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.60.242, server: t-ks.benlai.cloud, request: "GET /kapis/monitoring.kubesphere.io/v1alpha2/namespaces/kubesphere-devops-system?namespace=kubesphere-devops-system&start=1574279969.819&end=1574323169.819&step=4320s&times=10&metrics_filter=namespace_pod_count%7Cnamespace_deployment_count%7Cnamespace_statefulset_count%7Cnamespace_daemonset_count%7Cnamespace_job_count%7Cnamespace_cronjob_count%7Cnamespace_pvc_count%7Cnamespace_service_count%7Cnamespace_secret_count%7Cnamespace_configmap_count%7Cnamespace_ingresses_extensions_count%7Cnamespace_s2ibuilder_count%24 HTTP/1.1", upstream: "http://10.233.116.41:8000/kapis/monitoring.kubesphere.io/v1alpha2/namespaces/kubesphere-devops-system?namespace=kubesphere-devops-system&start=1574279969.819&end=1574323169.819&step=4320s&times=10&metrics_filter=namespace_pod_count%7Cnamespace_deployment_count%7Cnamespace_statefulset_count%7Cnamespace_daemonset_count%7Cnamespace_job_count%7Cnamespace_cronjob_count%7Cnamespace_pvc_count%7Cnamespace_service_count%7Cnamespace_secret_count%7Cnamespace_configmap_count%7Cnamespace_ingresses_extensions_count%7Cnamespace_s2ibuilder_count%24", host: "t-ks.benlai.cloud", referrer: "http://t-ks.benlai.cloud/projects/kubesphere-devops-system/overview"
```
2. 查看该 ks-console 实例的日志，有一些错误如下
```
ERR Error: Http response closed while proxying /kapis/monitoring.kubesphere.io/v1alpha2/namespaces/p2c-arch/workloads?type=rank&metrics_filter=workload_cpu_usage%7Cworkload_memory_usage_wo_cache%7Cworkload_net_bytes_transmitted%7Cworkload_net_bytes_received%7Creplica&page=1&limit=10&sort_type=desc&sort_metric=workload_cpu_usage
    at ServerResponse.n.res.on (/root/KubeSphereUI/server/server.js:352:1573)
    at emitNone (events.js:106:13)
    at ServerResponse.emit (events.js:208:7)
    at Socket.onServerResponseClose (_http_server.js:165:44)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
```
3. 再查看 ks-apiserver 日志，也有大量的错误日志
```
E1121 08:03:15.086046       1 project_pipeline_handler.go:248] client set not enabled: <nil>
E1121 08:03:15.086076       1 project_pipeline.go:149] [ServiceError:400] client set not enabled: <nil>
E1121 08:04:36.860301       1 devops.go:1085] {
  "message" : "Error processing Input Submit request. This Run instance does not have an Input with an id of '8030fb65ad0c23fe5f446735e7bcedd6'.",
  "code" : 400,
  "errors" : [ ]
}
E1121 08:04:36.860329       1 devops.go:558] {
  "message" : "Error processing Input Submit request. This Run instance does not have an Input with an id of '8030fb65ad0c23fe5f446735e7bcedd6'.",
  "code" : 400,
  "errors" : [ ]
}
E1121 08:04:36.860341       1 devops.go:640] {
  "message" : "Error processing Input Submit request. This Run instance does not have an Input with an id of '8030fb65ad0c23fe5f446735e7bcedd6'.",
  "code" : 400,
  "errors" : [ ]
}
E1121 08:04:42.665058       1 devops.go:1085] <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /crumbIssuer/api/json/. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
E1121 08:04:42.665079       1 devops.go:681] <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /crumbIssuer/api/json/. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
E1121 08:04:42.665092       1 devops.go:640] <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /crumbIssuer/api/json/. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
E1121 08:18:10.646304       1 project_pipeline_handler.go:248] client set not enabled: <nil>
E1121 08:18:10.646358       1 project_pipeline.go:149] [ServiceError:400] client set not enabled: <nil>
```

临时修复方式：
1. 重启 ks-apiserver
2. 重启 ks-console

**Comment by wansir** [comment]
组件启用时的中间状态
/milestone 3.0.0
