### ISSUE TITLE
使用官方例子构建流水线无法部署到kubernetes

### ISSUE THREAD

**Issue by leowucn** [kubesphere/kubesphere#1695]
**Describe the bug(描述下问题)**
参考的是这个例子
https://kubesphere.io/docs/v2.1/zh-CN/quick-start/devops-online/
但是最终在cicd的时候，流水线运行日志中 `deploy to dev`步骤报错，错误日志如下：
```
Starting Kubernetes deployment
ERROR: ERROR: java.lang.RuntimeException: java.io.IOException: PEM is invalid: no begin marker
hudson.remoting.ProxyException: java.lang.RuntimeException: java.io.IOException: PEM is invalid: no begin marker
	at io.kubernetes.client.util.credentials.ClientCertificateAuthentication.provide(ClientCertificateAuthentication.java:46)
	at io.kubernetes.client.util.credentials.KubeconfigAuthentication.provide(KubeconfigAuthentication.java:39)
	at io.kubernetes.client.util.ClientBuilder.build(ClientBuilder.java:300)
	at io.kubernetes.client.util.Config.fromConfig(Config.java:91)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.<init>(KubernetesClientWrapper.java:171)
	at com.microsoft.jenkins.kubernetes.KubernetesDeployContext$ClientWrapperFactoryImpl.buildClient(KubernetesDeployContext.java:482)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:143)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:124)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:106)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.244.3.179/10.244.3.179:58256
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.FilePath.act(FilePath.java:1160)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:68)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
Caused by: hudson.remoting.ProxyException: java.io.IOException: PEM is invalid: no begin marker
	at io.kubernetes.client.util.SSLUtils.decodePem(SSLUtils.java:179)
	at io.kubernetes.client.util.SSLUtils.loadKey(SSLUtils.java:113)
	at io.kubernetes.client.util.SSLUtils.createKeyStore(SSLUtils.java:152)
	at io.kubernetes.client.util.SSLUtils.createKeyStore(SSLUtils.java:92)
	at io.kubernetes.client.util.SSLUtils.keyManagers(SSLUtils.java:72)
	at io.kubernetes.client.util.credentials.ClientCertificateAuthentication.provide(ClientCertificateAuthentication.java:37)
	... 17 more
Kubernetes deployment ended with HasError
```

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by zryfish** [comment]
你的 devops 组件是后来启用的吧，这个错误看着是 kubeconfig 有问题，有按照文档创建ca证书么 https://github.com/kubesphere/ks-installer#enable-pluggable-components

**Comment by leowucn** [comment]
不是，devops是安装的时候就启用了。那两个secret也早已创建了

**Comment by zryfish** [comment]
看下你的流水线的凭证，kubeconfig是否正确，或者你换个用户登录试下

**Comment by leowucn** [comment]
确实是kubeconfig不对。创建demo-kubeconfig凭证的时候，凭证类型我选择了`kubeconfig`，我看下面Content自动加载了内容就没进一步去看是否是正确，因为我觉得kubesphere既然在管理集群，它当然是可以拿到正确的kubesphere的。

**Comment by leowucn** [comment]
所以，我需要手动粘贴kubeconfig到凭证Content那里吗？如果不需要，那这就是个bug了

**Comment by FeynmanZhou** [comment]
@leowucn 按道理应该是自动加载 kubeconfig 内容的，我们之前没有复现过，你可以再试试是否可以复现呢

**Comment by runzexia** [comment]
/unassign
/assign @wansir 
宏明帮忙统一看下这个kubeconfig 生成的问题吧，之前有其他用户遇到过 https://kubesphere.com.cn/forum/d/350-k8s/3

**Comment by leowucn** [comment]
@FeynmanZhou   可以复现，问题就是kubeconfig不对，我刚重新创建了一下kubeconfig，明显是错的，如下
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1USXhOakE0TkRNME1sb1hEVEk1TVRJeE16QTRORE0wTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSmNICnA5Y0tML2MycFFvTUlEL0JUQlRQaXF5TENWUWNad25wRmh0UTFPZ2hGU0psR2lBbDB3ZnNkTk5wUy9IeUxkUTcKVmdzMTAvMkh3V2NITHVabTFCdzhwYjFlL1lKbE1TT0dra0hVNkhBczQ2R0lHVVpFK3k2emFnREtsUDdwQmNVYwpqNFRnQkQwMUhjTnVIVndGQ0FkbmdEZ2lHM0Vubk9WNWsvTXo2cTFGR0ltemNYNGE4cndVcmloblNBblYxd2FOCmRtOFU2REhpcWV3U1dHUmZ1cW92alRkWHpoem5OZURHdXhvUlZZa3M3K1k2b1k4WUErRlA1bWdFLzNpSzZQa2sKWFZqMWwrOFNvWWFxOHBlTTRQWDFSdDdGUE5xNG4xOVJ0ejN0SXlsOHlMajFXZExpOUFKME9EK2g3U3hXdFlISgp3SGZ0TmtmL3hCOUVoK1N4QklrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBejRjRDlkRitWSTYxZnRWMTkwdmlVanhGQ3QKZWp1V2ErSGRLOWJ6dDRhdms2VG5nbkdOcmVWcEZKdllsRnBhaklLZ0JjRnArZ3RIL202VkQzMGI0Vm1oNUhEMApZQzZHTlNvUEd4MkIrTDJZNE9UTEM0dGtUNUlJU3Qyd1hldHdpVmE5U2VJOWIzLzFXOFJyYlJBeDllU2hZV01LCkdGcC9Vd3U2L0FuV2tERTBhNzVUcUFVYkticDlUTTZsR3BBQ3F3MUtLejFFRnNGblplNzNpRVppeTZuOHkzck0KL3Q4R1BIYnlDMTcyWDd5ZlgzbmVmbUs0cHJ3L1l5MnBWUDZiZzV5bzU4YStsa3dNYTdoT1NSTTdLV2xXWGd1SwpDUFBNOW5WbFJ4OVFhOVlSb2dzVkNEcm5NZVI4YVlweEEvS1R6NDZ0aXByNTJacDZHSnBTS1RzQ3V4cz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://10.96.0.1:443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
    namespace: default
  name: admin@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: ""
    client-key-data: ""
```

**Comment by scott-wong** [comment]
> @FeynmanZhou 可以复现，问题就是kubeconfig不对，我刚重新创建了一下kubeconfig，明显是错的，如下
> 
> ```
> apiVersion: v1
> clusters:
> - cluster:
>     certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1USXhOakE0TkRNME1sb1hEVEk1TVRJeE16QTRORE0wTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSmNICnA5Y0tML2MycFFvTUlEL0JUQlRQaXF5TENWUWNad25wRmh0UTFPZ2hGU0psR2lBbDB3ZnNkTk5wUy9IeUxkUTcKVmdzMTAvMkh3V2NITHVabTFCdzhwYjFlL1lKbE1TT0dra0hVNkhBczQ2R0lHVVpFK3k2emFnREtsUDdwQmNVYwpqNFRnQkQwMUhjTnVIVndGQ0FkbmdEZ2lHM0Vubk9WNWsvTXo2cTFGR0ltemNYNGE4cndVcmloblNBblYxd2FOCmRtOFU2REhpcWV3U1dHUmZ1cW92alRkWHpoem5OZURHdXhvUlZZa3M3K1k2b1k4WUErRlA1bWdFLzNpSzZQa2sKWFZqMWwrOFNvWWFxOHBlTTRQWDFSdDdGUE5xNG4xOVJ0ejN0SXlsOHlMajFXZExpOUFKME9EK2g3U3hXdFlISgp3SGZ0TmtmL3hCOUVoK1N4QklrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBejRjRDlkRitWSTYxZnRWMTkwdmlVanhGQ3QKZWp1V2ErSGRLOWJ6dDRhdms2VG5nbkdOcmVWcEZKdllsRnBhaklLZ0JjRnArZ3RIL202VkQzMGI0Vm1oNUhEMApZQzZHTlNvUEd4MkIrTDJZNE9UTEM0dGtUNUlJU3Qyd1hldHdpVmE5U2VJOWIzLzFXOFJyYlJBeDllU2hZV01LCkdGcC9Vd3U2L0FuV2tERTBhNzVUcUFVYkticDlUTTZsR3BBQ3F3MUtLejFFRnNGblplNzNpRVppeTZuOHkzck0KL3Q4R1BIYnlDMTcyWDd5ZlgzbmVmbUs0cHJ3L1l5MnBWUDZiZzV5bzU4YStsa3dNYTdoT1NSTTdLV2xXWGd1SwpDUFBNOW5WbFJ4OVFhOVlSb2dzVkNEcm5NZVI4YVlweEEvS1R6NDZ0aXByNTJacDZHSnBTS1RzQ3V4cz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
>     server: https://10.96.0.1:443
>   name: kubernetes
> contexts:
> - context:
>     cluster: kubernetes
>     user: admin
>     namespace: default
>   name: admin@kubernetes
> current-context: admin@kubernetes
> kind: Config
> preferences: {}
> users:
> - name: admin
>   user:
>     client-certificate-data: ""
>     client-key-data: ""
> ```

你好，我也遇到这个问题，对kubeconfig不太熟，默认生成的要怎么改才正确呢，谢谢

**Comment by wansir** [comment]
@leowucn  
这里admin 的 kubeconfig 的反序列化有问题， 可以从kubesphere-controls-system这个项目下kubeconfig-admin 这个 configmap 中直接复制出来

**Comment by wansir** [comment]
#1818 duplicated
/close
