### ISSUE TITLE
流水线执行失败

### ISSUE THREAD

**Issue by leowucn** [kubesphere/kubesphere#1718]
**Describe the bug(描述下问题)**
流水线 jenkinsfile内容为
```
pipeline {
  agent any
  stages {
    stage('拉取代码') {
      steps {
        git(url: 'http://xxx.xxx.xxx.xxx:10080/root/test_k8s.git', credentialsId: 'gitlab-id', changelog: true, poll: false)
      }
    }
    stage('测试') {
      steps {
        sh 'ls -al'
      }
    }
    stage('部署') {
      steps {
        kubernetesDeploy(enableConfigSubstitution: true, deleteResource: false, kubeconfigId: 'kubeconfig-demo', configs: '-f namespace.yaml -f flask1.yaml')
      }
    }
  }
}
```
流水线最后一个阶段报错如下
```
Starting Kubernetes deployment
ERROR: ERROR: java.lang.IllegalStateException: No matching configuration files found for -f namespace.yaml -f flask1.yaml
hudson.remoting.ProxyException: java.lang.IllegalStateException: No matching configuration files found for -f namespace.yaml -f flask1.yaml
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:152)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:124)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:106)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.244.3.50/10.244.3.50:44534
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.FilePath.act(FilePath.java:1160)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:68)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
ERROR: No matching configuration files found for -f namespace.yaml -f flask1.yaml
Kubernetes deployment ended with HasError


```

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by minghaoye** [comment]
kubernetesDeploy 这个步骤的 configs 填写的是`配置文件路径`，
![Screen Shot 2019-12-26 at 11 24 39 AM](https://user-images.githubusercontent.com/22934997/71455988-53c11680-27d2-11ea-9607-cb2fca136bc7.png)

可以参考这个示例
https://github.com/kubesphere/devops-java-sample/blob/master/Jenkinsfile-online#L84

**Comment by leowucn** [comment]
你这个应该是可以的，但是我记得之前有一次我那种方式是可以工作的，后来集群重新部署了

**Comment by minghaoye** [comment]
直接填写`namespace.yaml flask1.yaml`呢？

**Comment by leowucn** [comment]
不行，错误和上面的一样`No matching configuration files found for namespace.yaml flask1.yaml`

**Comment by soulseen** [comment]
你的目录结构是什么样的？configs: 'PATH/TO/*.yaml'

**Comment by leowucn** [comment]
<img width="1265" alt="Snipaste_2019-12-26_11-51-49" src="https://user-images.githubusercontent.com/16133390/71456790-24140d80-27d6-11ea-984a-b6745ebe2f82.png">
<img width="1261" alt="Snipaste_2019-12-26_11-52-21" src="https://user-images.githubusercontent.com/16133390/71456800-30986600-27d6-11ea-86ef-52071951c017.png">

**Comment by soulseen** [comment]
配置 configs: '*.yaml' 试一下。

**Comment by leowucn** [comment]
在哪里配置？jenkinsfile?我不熟悉jenkinsfile语法

**Comment by leowucn** [comment]
我希望能完全通过界面配置流水线

**Comment by soulseen** [comment]
```
kubernetesDeploy(enableConfigSubstitution: true, deleteResource: false, kubeconfigId: 'kubeconfig-demo', configs: '*.yaml')
```
可以修改jenkinsfile，也可以在界面上修改。
参考这里的回复，config配置的是yaml的路径

> kubernetesDeploy 这个步骤的 configs 填写的是`配置文件路径`，
> ![Screen Shot 2019-12-26 at 11 24 39 AM](https://user-images.githubusercontent.com/22934997/71455988-53c11680-27d2-11ea-9607-cb2fca136bc7.png)
> 
> 可以参考这个示例
> https://github.com/kubesphere/devops-java-sample/blob/master/Jenkinsfile-online#L84

**Comment by leowucn** [comment]
@soulseen 我需要apply指定yaml文件，你这个`configs: '*.yaml'`会apply所有yaml文件吧

**Comment by soulseen** [comment]
嗯，指定多个文件可以用(,)分割

**Comment by soulseen** [comment]
可以参考下这个https://github.com/jenkinsci/kubernetes-cd-plugin#configure-the-plugin

**Comment by leowucn** [comment]
还是不对，流水线执行报错
<img width="750" alt="Snipaste_2019-12-26_12-05-48" src="https://user-images.githubusercontent.com/16133390/71457294-25463a00-27d8-11ea-9ed3-aa03b4059e13.png">
```
Starting Kubernetes deployment
Loading configuration: /home/jenkins/agent/workspace/project-R2k57KywpXZZ/test/flask1.yaml
ERROR: ERROR: java.lang.RuntimeException: io.kubernetes.client.ApiException: Not Found
hudson.remoting.ProxyException: java.lang.RuntimeException: io.kubernetes.client.ApiException: Not Found
	at com.microsoft.jenkins.kubernetes.wrapper.ResourceManager.handleApiException(ResourceManager.java:193)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$ServiceUpdater.createResource(V1ResourceManager.java:453)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$ServiceUpdater.createResource(V1ResourceManager.java:371)
	at com.microsoft.jenkins.kubernetes.wrapper.ResourceManager$ResourceUpdater.createOrApply(ResourceManager.java:100)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.handleResource(KubernetesClientWrapper.java:289)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:256)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:172)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:124)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:106)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.244.3.61/10.244.3.61:51770
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.FilePath.act(FilePath.java:1160)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:68)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
Caused by: hudson.remoting.ProxyException: io.kubernetes.client.ApiException: Not Found
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:886)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:802)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedServiceWithHttpInfo(CoreV1Api.java:9415)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedService(CoreV1Api.java:9397)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$ServiceUpdater.createResource(V1ResourceManager.java:450)
	... 16 more
Api call failed with code 404, detailed message: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "namespaces \"test\" not found",
  "reason": "NotFound",
  "details": {
    "name": "test",
    "kind": "namespaces"
  },
  "code": 404
}
Kubernetes deployment ended with HasError
```

**Comment by soulseen** [comment]
这个就是namespace not found ，文件读取是正常的，把namespace的问题修复下就可以了

**Comment by leowucn** [comment]
那俩yaml文件，我专门把namespace.yaml放在了前面就是为了先执行它创建指定命名空间。我觉得这种需求没问题吧

**Comment by soulseen** [comment]
嗯，这个可能也是cd插件没有考虑到的地方。不过一般不建议用流水线去部署namespace，namespace也不会去频繁的更新，可以先手动创建ns，然后用流水线部署应用。

**Comment by leowucn** [comment]
可以，但是希望你们能加上这种特性，因为用户执行yaml不会按照特定的规律，否则其他人也会报各种奇奇怪怪的错误了
