### ISSUE TITLE
 openpitrix-repo-db-ctrl-job 执行失败

### ISSUE THREAD

**Issue by RikyLee** [kubesphere/kubesphere#1730]
kubesphere  版本2.1，在现有的kubernetes 1.15.5 环境下运行

执行kubectl logs -f openpitrix-repo-db-ctrl-job-kdrsp -n openpitrix-system，显示如下异常信息：

Current version of schema `repo`: 0.1
DEBUG: Memory usage: 42 of 972M
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Schema `repo` contains a failed migration to version 0.1 !
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:227)
        at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
        at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
        at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:161)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:189)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:149)
        at org.flywaydb.core.Flyway.execute(Flyway.java:511)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:149)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:176)
        at org.flywaydb.commandline.Main.main(Main.java:123)

**Comment by RikyLee** [comment]
执行kubectl -n openpitrix-system get job openpitrix-repo-db-ctrl-job -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f - 强行更新数据库无效
