### ISSUE TITLE
执行uninstall.sh脚本，卸载操作，重置防火墙iptables，导致主机失联

### ISSUE THREAD

**Issue by zhangpfly** [kubesphere/kubesphere#1731]
主机环境：4核8G*6台

问题：
在清理环境，执行卸载操作的时候，卡在了TASK [reset : flush iptables]这一步，直接导致要卸载的主机失联，ssh无法连接过去，ping也不通，只能重启主机，才能重新连接。
执行卸载操作之前，已经关闭了主机防火墙。

想问一下，这一步都执行了什么操作？为什么会导致主机失联？
而且这个问题，碰到多次了，感觉很麻烦。麻烦看一下

日志如下：
```
TASK [reset : reset | unmount kubelet dirs] *****************************************************************************************************************************
Monday 30 December 2019  14:56:21 +0800 (0:00:00.420)       0:00:17.201 ******* 

TASK [reset : flush iptables] *******************************************************************************************************************************************
Monday 30 December 2019  14:56:21 +0800 (0:00:00.168)       0:00:17.370 ******* 
changed: [test05] => (item=filter)
changed: [test07] => (item=filter)
changed: [test06] => (item=filter)
changed: [test05] => (item=nat)
changed: [test06] => (item=nat)
changed: [test07] => (item=nat)
^CProcess WorkerProcess-144:
Process WorkerProcess-143:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
 [ERROR]: User interrupted execution

    self.run()
    self.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 118, in run
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 118, in run
    self._final_q
    self._final_q
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 106, in run
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 106, in run
    item_results = self._run_loop(items)
    item_results = self._run_loop(items)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 343, in _run_loop
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 343, in _run_loop
    res = self._execute(variables=task_vars)
    res = self._execute(variables=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 857, in _execute_module
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 857, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 976, in _low_level_execute_command
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 976, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1145, in exec_command
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1145, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 392, in wrapped
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 392, in wrapped
    return_tuple = func(self, *args, **kwargs)
    return_tuple = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1035, in _run
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1035, in _run
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 872, in _bare_run
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 872, in _bare_run
    events = selector.select(timeout)
    events = selector.select(timeout)
  File "/usr/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 466, in select
  File "/usr/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 466, in select
    maxevents=max_events)
  File "/usr/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 119, in _syscall_wrapper
    result = func(*args, **kwargs)
KeyboardInterrupt
    maxevents=max_events)
  File "/usr/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 119, in _syscall_wrapper
    result = func(*args, **kwargs)

```

**Comment by zhangpfly** [comment]
kubsphere版本：2.1.0

**Comment by Forest-L** [comment]
卸载那些iptables规则

**Comment by zhangpfly** [comment]
问题已解决
修改配置文件：vim ./k8s/roles/reset/defaults/main.yml
flush_iptables: false  # true改为false
还是用手动清理防火墙规则吧。

清理之前参考：https://www.cnblogs.com/fazero/p/10449931.html
iptables规则清理，不要直接用iptables -F，否则会导致主机失联

iptables -P INPUT ACCEPT
iptables -F

这样就不会失联了。
再执行
ipvsadm -C
ip link delete kube-ipvs0
