### ISSUE TITLE
kubesphere 多节点安装的时候显示pip 安装出错 

### ISSUE THREAD

**Issue by chinazj** [kubesphere/kubesphere#1758]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

kubesphere 安装的时候显示python2.7 退出历史舞台

安装环境的硬件配置
操作系统：centos7.7，kvm虚拟机
![image](https://user-images.githubusercontent.com/15140157/72242761-2a531800-3625-11ea-8bea-5c21b1aea609.png)
cpu相关：
![image](https://user-images.githubusercontent.com/15140157/72242727-160f1b00-3625-11ea-9fa2-b0cdd9d9c9a2.png)
内存相关：
![image](https://user-images.githubusercontent.com/15140157/72242798-3ccd5180-3625-11ea-8a51-6d8dfbd3c409.png)
磁盘
![image](https://user-images.githubusercontent.com/15140157/72242889-65554b80-3625-11ea-8fb7-23cb82fffd46.png)

错误信息：
TASK [prepare/nodes : pip | Installing pip] ***********************************************************************************************
Monday 13 January 2020  15:23:38 +0800 (0:00:08.503)       0:02:51.016 ******** 
 [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running sudo

changed: [master]
fatal: [node1]: FAILED! => {
    "changed": true, 
    "cmd": "sudo python /tmp/pip/get-pip.py", 
    "delta": "0:00:42.838797", 
    "end": "2020-01-13 15:24:22.713916", 
    "rc": 2, 
    "start": "2020-01-13 15:23:39.875119"
}

STDOUT:

Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)

STDERR:

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/operations/prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/download.py", line 1064, in unpack_url
    progress_bar=progress_bar
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/download.py", line 924, in unpack_http_url
    progress_bar)
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/download.py", line 1152, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/download.py", line 861, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/utils/hashes.py", line 75, in check_against_chunks
    for chunk in chunks:
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/download.py", line 829, in written_chunks
    for chunk in chunks:
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/utils/ui.py", line 156, in iter
    for x in it:
  File "/tmp/tmpL7m26w/pip.zip/pip/_internal/download.py", line 818, in resp_read
    decode_content=False):
  File "/tmp/tmpL7m26w/pip.zip/pip/_vendor/urllib3/response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/tmp/tmpL7m26w/pip.zip/pip/_vendor/urllib3/response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/tmpL7m26w/pip.zip/pip/_vendor/urllib3/response.py", line 411, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

MSG:

non-zero return code

fatal: [node2]: FAILED! => {
    "changed": true, 
    "cmd": "sudo python /tmp/pip/get-pip.py", 
    "delta": "0:00:44.399322", 
    "end": "2020-01-13 15:24:24.592359", 
    "rc": 2, 
    "start": "2020-01-13 15:23:40.193037"
}

STDOUT:

Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)

STDERR:

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/operations/prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/download.py", line 1064, in unpack_url
    progress_bar=progress_bar
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/download.py", line 924, in unpack_http_url
    progress_bar)
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/download.py", line 1152, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/download.py", line 861, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/utils/hashes.py", line 75, in check_against_chunks
    for chunk in chunks:
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/download.py", line 829, in written_chunks
    for chunk in chunks:
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/utils/ui.py", line 156, in iter
    for x in it:
  File "/tmp/tmpagWWfX/pip.zip/pip/_internal/download.py", line 818, in resp_read
    decode_content=False):
  File "/tmp/tmpagWWfX/pip.zip/pip/_vendor/urllib3/response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/tmp/tmpagWWfX/pip.zip/pip/_vendor/urllib3/response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/tmpagWWfX/pip.zip/pip/_vendor/urllib3/response.py", line 411, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

MSG:

non-zero return code

Installer版本:kubesphere-v2.1。多节点在线安装

**Comment by Forest-L** [comment]
再跑脚本重安装下即可。

**Comment by chinazj** [comment]
好像是网络的问题，多次执行python /tmp/pip/get-pip.py可以成功。
