### ISSUE TITLE
kubesphere2.1多节点安装报错idna、cryptography、dnspython、python-ldap版本太低

### ISSUE THREAD

**Issue by Tangroo** [kubesphere/kubesphere#1764]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
多节点执行安装脚本后不久就报错，说idna、cryptography、dnspython、python-ldap这些版本不符合要求。最后报错'platform_system' is not defined

**安装环境的硬件配置**
2master
3node
2core
4G内存
centos7.6
VMware虚拟机
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
  Downloading https://mirrors.aliyun.com/pypi/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
     |████████████████████████████████| 163kB 18.4MB/s 
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography->ansible==2.7.12->-r os/requirements.txt (line 1)) (2.14)
Building wheels for collected packages: ansible
  Building wheel for ansible (setup.py) ... done
  Created wheel for ansible: filename=ansible-2.7.12-cp27-none-any.whl size=9439160 sha256=97f185990ac6e7d47891bd125e77729e0d220249c840c26eb6a724d41ad07eb9
  Stored in directory: /root/.cache/pip/wheels/ab/0d/30/f1dac00a1e2f30d0d909d545393667e740cc92a2ac857843a8
Successfully built ansible
ERROR: requests 2.22.0 has requirement idna<2.9,>=2.5, but you'll have idna 2.4 which is incompatible.
ERROR: paramiko 2.7.1 has requirement cryptography>=2.5, but you'll have cryptography 1.7.2 which is incompatible.
ERROR: ipapython 4.6.4 has requirement dnspython>=1.15, but you'll have dnspython 1.12.0 which is incompatible.
ERROR: ipapython 4.6.4 has requirement python-ldap>=3.0.0b1, but you'll have python-ldap 2.4.15 which is incompatible.
Installing collected packages: MarkupSafe, jinja2, pynacl, bcrypt, paramiko, ansible, netaddr, pbr, chardet, urllib3, certifi, requests, hvac, jmespath, ruamel.ordereddict, ruamel.yaml
  Found existing installation: netaddr 0.7.5
ERROR: Cannot uninstall 'netaddr'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
*********************************************
1. Initiating Environment
*********************************************
ERROR! Unexpected Exception, this is probably a bug: name 'platform_system' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 97, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 38, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 38, in <module>
    from ansible.plugins.loader import inventory_loader
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 22, in <module>
    from ansible.parsing.utils.yaml import from_yaml
  File "/usr/lib/python2.7/site-packages/ansible/parsing/utils/yaml.py", line 17, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/constructor.py", line 29, in <module>
    from ansible.parsing.vault import VaultLib
  File "/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 42, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2489, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2700, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2733, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2730, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/usr/lib/python2.7/site-packages/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'platform_system' is not defined
failed!
**********************************
please refer to https://kubesphere.io/docs/v2.1/zh-CN/faq/faq-install/
**********************************

**Installer版本**

**Comment by yunkunrao** [comment]
From the error log, it seems that idna, cryptography version are too low. Could you please first upgrade these modules? I think the following ansible errors  are produced because of this  version compatibility problem.
