### ISSUE TITLE
异常登录不了

### ISSUE THREAD

**Issue by qqqlllei** [kubesphere/kubesphere#1793]
ERR Error: Http response closed while proxying /kapis/resources.kubesphere.io/v1alpha2/namespaces/demo/pods?conditions=ownerKind%3DDeployment%2CownerName%3Ddemo-b-bfjaet&paging=limit%3D10%2Cpage%3D1
    at ServerResponse.n.res.on (/root/KubeSphereUI/server/server.js:352:1573)
    at emitNone (events.js:106:13)
    at ServerResponse.emit (events.js:208:7)
    at Socket.onServerResponseClose (_http_server.js:165:44)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)

ERR Error: Http response closed while proxying /kapis/resources.kubesphere.io/v1alpha2/componenthealth
    at ServerResponse.n.res.on (/root/KubeSphereUI/server/server.js:352:1573)
    at emitNone (events.js:106:13)
    at ServerResponse.emit (events.js:208:7)
    at Socket.onServerResponseClose (_http_server.js:165:44)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)

报了这个错后，在登陆就没反应了
后台log 显示 ERR { code: 502, statusText: 'Bad Gateway', message: '502 Bad Gateway\n' }

都是ks-console 的错误信息

**Comment by leoendless** [comment]
检查 kubesphere  各个服务组件的状态是否正常
