### ISSUE TITLE
Add  user to ldap 

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#2198]
```bash
org.acegisecurity.userdetails.UsernameNotFoundException: User admin not found in directory.
	at org.acegisecurity.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:126)
	at hudson.security.LDAPSecurityRealm$LDAPUserDetailsService.loadUserByUsername(LDAPSecurityRealm.java:1314)
	at hudson.security.LDAPSecurityRealm$LDAPUserDetailsService.loadUserByUsername(LDAPSecurityRealm.java:1251)
	at jenkins.security.ImpersonatingUserDetailsService.loadUserByUsername(ImpersonatingUserDetailsService.java:30)
	at hudson.model.User.getUserDetailsForImpersonation(User.java:394)
```

DevOps use LDAP to manager users. It is necessary to sync users from Auth to OpenLDAP

version: 20200613 installer 
/area  iam
/assign @wansir

**Comment by wansir** [comment]
Veryfied [reverse-proxy-auth-plugin](https://plugins.jenkins.io/reverse-proxy-auth-plugin/) is working.
