### ISSUE TITLE
Internal error occurred: account is not active

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#2600]
* When login in, Internal error occurred: account is not active.
* all pod running.
* v3.0.0
![image](https://user-images.githubusercontent.com/50984129/88392386-7c53d200-cdee-11ea-8678-0237ab4be037.png)

* ks-console log
![image](https://user-images.githubusercontent.com/50984129/88392421-8f66a200-cdee-11ea-92e1-a14b074eccc2.png)

* ks-apiserver log
![image](https://user-images.githubusercontent.com/50984129/88392489-aa391680-cdee-11ea-9920-210a57a5bb03.png)

**Comment by Forest-L** [comment]
The latest version has been fixed

**Comment by willzhang** [comment]
not fixed
```
Dashboard app running at port 8000
  <-- GET / 2020/09/16T23:17:45.390
{ UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
    at renderView (/opt/kubesphere/console/server/server.js:23231:46)
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
  --> GET / 302 11ms 43b 2020/09/16T23:17:45.401
  <-- GET /login 2020/09/16T23:17:45.403
{ FetchError: request to http://ks-apiserver.kubesphere-system.svc/kapis/config.kubesphere.io/v1alpha2/configs/oauth failed, reason: connect ECONNREFUSED 10
.104.204.81:80
    at ClientRequest.<anonymous> (/opt/kubesphere/console/server/server.js:80604:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  message: 'request to http://ks-apiserver.kubesphere-system.svc/kapis/config.kubesphere.io/v1alpha2/configs/oauth failed, reason: connect ECONNREFUSED 10.1
04.204.81:80',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
  --> GET /login 200 1,025ms 14.82kb 2020/09/16T23:17:46.428
  <-- GET / 2020/09/16T23:17:55.377
{ UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
--More--
```

**Comment by pytimer** [comment]
@Forest-L I follow the kubesphere doc https://kubesphere.io/docs/quick-start/minimal-kubesphere-on-k8s/ to deploy kubesphere on my own kubernetes cluster. It also have this question.

The kubesphere images:
```sh
kubesphere/ks-installer                                v3.0.0              893b46ffa208        6 weeks ago         692MB
kubesphere/ks-controller-manager                       v3.0.0              85bd13080839        2 months ago        82MB
kubesphere/ks-apiserver                                v3.0.0              d9fac59cfb8c        2 months ago        120MB
kubesphere/ks-console                                  v3.0.0              d5987e1f99ac        2 months ago        95.5MB
```

**Comment by Forest-L** [comment]
@pytimer   What happened?
```
You can run this command:
kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f
```

**Comment by pytimer** [comment]
Sorry to reply late.
The ks-installer logs:
```sh
**************************************************
#####################################################
###              Welcome to KubeSphere!           ###
#####################################################

Console: http://10.33.41.234:30880
Account: admin
Password: P@88w0rd

NOTES：
  1. After logging into the console, please check the
     monitoring status of service components in
     the "Cluster Management". If any service is not
     ready, please wait patiently until all components
     are ready.
  2. Please modify the default password after login.

#####################################################
https://kubesphere.io             2020-10-30 15:31:30
#####################################################
```

I see ks-install show success. 
I found the `ks-controller-manager-586d774757-8c6rf` pod have the error log `error syncing 'admin': Internal error occurred: failed calling webhook "validating-user.k  ubesphere.io": Post https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=4s: context   deadline exceeded, requeuing`, i try to curl this api, it works. But when i delete this pod and recreate ks-controller-manager pod, everything works well.
