### ISSUE TITLE
kubesphere 1.0.1版本openpitrix-iam-service-deployment容器无法启动

### ISSUE THREAD

**Issue by JieHry** [kubesphere/kubesphere#271]
查看openpitrix-iam-service-deployment日志发现无法找到iam.user表。
`2019-01-14 01:25:42.25938 -INFO- Release OpVersion: [v0.3.5] (grpc_server.go:79)
2019-01-14 01:25:42.25957 -INFO- Git Commit Hash: [9333eae7354fc6634785df7a2fef35e74ed8dce5] (grpc_server.go:79)
2019-01-14 01:25:42.25966 -INFO- Build Time: [2018-11-22 06:37:13] (grpc_server.go:79)
2019-01-14 01:25:42.25974 -INFO- Service [iam-service] start listen at port [9115] (grpc_server.go:81)
2019-01-14 01:25:42.27191 -ERROR- Error 1146: Table 'iam.user' doesn't exist (event.go:36)
2019-01-14 01:25:42.27192 -ERROR- Error 1146: Table 'iam.user_client' doesn't exist (event.go:36)
2019-01-14 01:25:42.27371 -ERROR- dbr.select.load.query: map[sql:SELECT user_id, username, password, email, role, description, status, create_time, update_time, status_time FROM user WHERE (`email` = 'admin@op.com')] (event.go:37)
panic: Error 1146: Table 'iam.user' doesn't exist

goroutine 377 [running]:
openpitrix.io/openpitrix/pkg/service/iam.initIAMAccount()
	/go/src/openpitrix.io/openpitrix/pkg/service/iam/init.go:78 +0xdc3
created by openpitrix.io/openpitrix/pkg/service/iam.Serve
	/go/src/openpitrix.io/openpitrix/pkg/service/iam/server.go:25 +0x5f`

**Comment by calvinyv** [comment]
可否执行一下 kubectl get pods -n openpitrix-system看一下返回，涉及到openpitrix的组件的任务可能有些没有执行完

如果可以，可以将环境访问信息邮件发到 kubesphere@yunify.com，我们上去debug一下

**Comment by JieHry** [comment]
重新执行安装程序后，就可以正常启动了。应该就是您说的有些任务没有执行完成。
