### ISSUE TITLE
can't rerun failed pipeline 

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2777]
**Describe the Bug**
Click rerun the failed piple and got the following error msg. But clicking on the successful pipeline is fine.
<img width="1198" alt="Screen Shot 2020-08-05 at 6 05 49 PM" src="https://user-images.githubusercontent.com/28859385/89400498-8eb30180-d746-11ea-8934-bc93bd8724bc.png">

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by harrisonliu5** [comment]
[POST] http://139.198.14.155:30885/kapis/devops.kubesphere.io/v1alpha2/devops/demo-devops767p6/pipelines/demo-devops/branches/master/runs/3/replay/

@shaowenchen

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/89481435-46d5be00-d7ca-11ea-88e9-ebf193e8b453.png)

It works in my env. Is there any pattern in which this happens?

**Comment by rayzhou2017** [comment]
It might be user permission problem. I am using self provisioner. Maybe you are using admin?

**Comment by shaowenchen** [comment]
```log
Started by user ha:////*************LzUIgDiCWt9zgAAAA==ws-self-provisioner
Replayed ha:////*********vLUpO1XPPLPEoTXLOzyvOz0n1yy9JZYAARiYGRi8GzpLM3NTiksTcgooiBqmM0pTi/Dy9ZIhiPayaGCoKgHTxwVb3SAAK2dkbjgAAAA==Connecting to https://api.github.com using /******
Obtained Jenkinsfile-online from ca5c9d0b38bf145fdd60a35de6c4d24f7c0067f0
Running in Durability level: MAX_SURVIVABILITY

GitHub has been notified of this commit’s build result

java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
        at hudson.util.FileChannelWriter.write(FileChannelWriter.java:72)
        at java.io.Writer.write(Writer.java:192)
        at hudson.util.AtomicFileWriter.write(AtomicFileWriter.java:162)
        at java.io.Writer.write(Writer.java:157)
        at hudson.XmlFile.write(XmlFile.java:189)
        at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:30)
        at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage.writeNode(SimpleXStreamFlowNodeStorage.java:182)
        at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage.flushNode(SimpleXStreamFlowNodeStorage.java:151)
        at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage.storeNode(SimpleXStreamFlowNodeStorage.java:125)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$TimingFlowNodeStorage.storeNode(CpsFlowExecution.java:1827)
        at org.jenkinsci.plugins.workflow.cps.FlowHead.newStartNode(FlowHead.java:119)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:530)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:320)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

**Comment by rayzhou2017** [comment]
what is reason?

**Comment by shaowenchen** [comment]
Replay function depends on the workflow file. But if an exception occurs during initialization, there will be no workflow file, e.g unable to access api.github.com.

Replay in Jenkins BlueOcean will also report an error.

We need to find a way to disable replay in this situation or push the community to solve it.

**Comment by zryfish** [comment]
watching
