### ISSUE TITLE
Internal error when toggle s2i event detail

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#2853]
**Describe the Bug**
```
2020/08/11 16:01:10 http: panic serving 10.233.70.8:55508: runtime error: invalid memory address or nil pointer dereference
goroutine 3807 [running]:
net/http.(*conn).serve.func1(0xc0026f2dc0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139
panic(0x2d34d80, 0x544b7a0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
kubesphere.io/kubesphere/pkg/models/logging.loggingOperator.SearchLogs(...)
	/home/runner/work/kubesphere/kubesphere/pkg/models/logging/logging.go:55
kubesphere.io/kubesphere/pkg/models/tenant.(*tenantOperator).QueryLogs(0xc000aac200, 0x38d28c0, 0xc002607300, 0xc002799300, 0xc002607300, 0x1, 0x0)
	/home/runner/work/kubesphere/kubesphere/pkg/models/tenant/tenant.go:765 +0xa7a
kubesphere.io/kubesphere/pkg/kapis/tenant/v1alpha2.(*tenantHandler).QueryLogs(0xc000a9a9d0, 0xc002718090, 0xc0006ff880)
	/home/runner/work/kubesphere/kubesphere/pkg/kapis/tenant/v1alpha2/handler.go:352 +0x1eb
github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc002718090, 0xc0006ff880)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:283 +0x3e
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc002718120, 0xc002718090, 0xc0006ff880)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:21 +0x8b
kubesphere.io/kubesphere/pkg/apiserver.logRequestAndResponse(0xc002718090, 0xc0006ff880, 0xc002718120)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/apiserver.go:531 +0x82
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc002718120, 0xc002718090, 0xc0006ff880)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:19 +0x65
github.com/emicklei/go-restful.(*Container).dispatch(0xc00089c000, 0x38bf040, 0xc00147c460, 0xc000e13d00)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:285 +0x866
net/http.HandlerFunc.ServeHTTP(0xc000a9b320, 0x38bf040, 0xc00147c460, 0xc000e13d00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000868d80, 0x38bf040, 0xc00147c460, 0xc000e13d00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2416 +0x1bd
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc00089c000, 0x38bf040, 0xc00147c460, 0xc000e13d00)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:303 +0x4d
kubesphere.io/kubesphere/pkg/apiserver/filters.WithKubeAPIServer.func1(0x38bf040, 0xc00147c460, 0xc000e13d00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/kubeapiserver.go:71 +0x37f
net/http.HandlerFunc.ServeHTTP(0xc0000add00, 0x38bf040, 0xc00147c460, 0xc000e13d00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x38bf040, 0xc00147c460, 0xc000e13d00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authorization.go:50 +0x37c
net/http.HandlerFunc.ServeHTTP(0xc0000ade00, 0x38bf040, 0xc00147c460, 0xc000e13d00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x38bf040, 0xc00147c460, 0xc000e13a00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authentication.go:95 +0xb6b
net/http.HandlerFunc.ServeHTTP(0xc00085eb90, 0x38bf040, 0xc00147c460, 0xc000e13a00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x38bf040, 0xc00147c460, 0xc000e13600)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc000367b30, 0x38bf040, 0xc00147c460, 0xc000e13600)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc00089a000, 0x38bf040, 0xc00147c460, 0xc000e13600)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc0026f2dc0, 0x38d1c40, 0xc002607180)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384
2020/08/11 16:01:50 http: panic serving 10.233.70.8:55938: runtime error: invalid memory address or nil pointer dereference
goroutine 4034 [running]:
net/http.(*conn).serve.func1(0xc0026f3040)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139
panic(0x2d34d80, 0x544b7a0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
kubesphere.io/kubesphere/pkg/models/logging.loggingOperator.SearchLogs(...)
	/home/runner/work/kubesphere/kubesphere/pkg/models/logging/logging.go:55
kubesphere.io/kubesphere/pkg/models/tenant.(*tenantOperator).QueryLogs(0xc000aac200, 0x38d28c0, 0xc003087f80, 0xc002e66800, 0xc003087f80, 0x1, 0x0)
	/home/runner/work/kubesphere/kubesphere/pkg/models/tenant/tenant.go:765 +0xa7a
kubesphere.io/kubesphere/pkg/kapis/tenant/v1alpha2.(*tenantHandler).QueryLogs(0xc000a9a9d0, 0xc0031d4c90, 0xc000492c40)
	/home/runner/work/kubesphere/kubesphere/pkg/kapis/tenant/v1alpha2/handler.go:352 +0x1eb
github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc0031d4c90, 0xc000492c40)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:283 +0x3e
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0031d4d20, 0xc0031d4c90, 0xc000492c40)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:21 +0x8b
kubesphere.io/kubesphere/pkg/apiserver.logRequestAndResponse(0xc0031d4c90, 0xc000492c40, 0xc0031d4d20)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/apiserver.go:531 +0x82
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0031d4d20, 0xc0031d4c90, 0xc000492c40)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:19 +0x65
github.com/emicklei/go-restful.(*Container).dispatch(0xc00089c000, 0x38bf040, 0xc002f09260, 0xc003537400)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:285 +0x866
net/http.HandlerFunc.ServeHTTP(0xc000a9b320, 0x38bf040, 0xc002f09260, 0xc003537400)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000868d80, 0x38bf040, 0xc002f09260, 0xc003537400)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2416 +0x1bd
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc00089c000, 0x38bf040, 0xc002f09260, 0xc003537400)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:303 +0x4d
kubesphere.io/kubesphere/pkg/apiserver/filters.WithKubeAPIServer.func1(0x38bf040, 0xc002f09260, 0xc003537400)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/kubeapiserver.go:71 +0x37f
net/http.HandlerFunc.ServeHTTP(0xc0000add00, 0x38bf040, 0xc002f09260, 0xc003537400)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x38bf040, 0xc002f09260, 0xc003537400)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authorization.go:50 +0x37c
net/http.HandlerFunc.ServeHTTP(0xc0000ade00, 0x38bf040, 0xc002f09260, 0xc003537400)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x38bf040, 0xc002f09260, 0xc003537300)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authentication.go:95 +0xb6b
net/http.HandlerFunc.ServeHTTP(0xc00085eb90, 0x38bf040, 0xc002f09260, 0xc003537300)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x38bf040, 0xc002f09260, 0xc003537200)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc000367b30, 0x38bf040, 0xc002f09260, 0xc003537200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc00089a000, 0x38bf040, 0xc002f09260, 0xc003537200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc0026f3040, 0x38d1c40, 0xc003087e00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384
```

**Versions Used**
KubeSphere: 3.0.0

**Environment**

```
  logging:
    enabled: false
```

**How To Reproduce**

Request URL: http://192.168.0.2:30880/kapis/tenant.kubesphere.io/v1alpha2/logs?namespaces=z1&pods=laizhengyi-devops-java-sample-latest--abd-aed1f576a108-jobs2bdb&timestamps=true&tailLines=1000&size=300&from=0&sort=asc

![截屏2020-08-12 00 06 46](https://user-images.githubusercontent.com/4156721/89921059-cd0d5c80-dc2f-11ea-8375-f21ab68d45b2.png)

**Expected behavior**

No error

**Comment by huanggze** [comment]
/assign @harrisonliu5 
Should hide s2i build logs when logging is not enabled

**Comment by zheng1** [comment]
verified
/close
