### ISSUE TITLE
Create volume reports an error

### ISSUE THREAD

**Issue by cumirror** [kubesphere/kubesphere#2973]
**Describe the Bug**
Create volume through UI report error:
![image](https://user-images.githubusercontent.com/2455429/92886492-41613880-f446-11ea-8c86-671fd7ed883c.png)

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: k8s 1.19

**ks-api log**
```
2020/09/11 14:43:17 http: panic serving 10.22.82.241:56576: runtime error: invalid memory address or nil pointer dereference
goroutine 6300 [running]:
net/http.(*conn).serve.func1(0xc0006ed0e0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139
panic(0x2d36da0, 0x5450320)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/storageclass.(*storageClassesSearcher).countPersistentVolumeClaims(0xc0008c2440, 0xc000b79800, 0x13, 0x54c6d68)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/storageclass/storageclasses.go:110 +0x12c
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/storageclass.(*storageClassesSearcher).Search(0xc0008c2440, 0x0, 0x0, 0xc0016bbdd0, 0xc001fdee82, 0xa, 0x1, 0x2e5db20, 0xc001f936e0, 0x0, ...)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/storageclass/storageclasses.go:92 +0x2f0
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/resource.(*ResourceGetter).ListResources(0xc0000d0160, 0x0, 0x0, 0xc001fdee6c, 0xe, 0xc0016bbdd0, 0xc001fdee82, 0xa, 0x299a801, 0xa, ...)
	/home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/resource/resources.go:123 +0x23e
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).fallback(0xc0008c2460, 0xc001fdee6c, 0xe, 0x0, 0x0, 0xc002ba0600, 0x0, 0x3856240, 0xc000529bf0)
	/home/runner/work/kubesphere/kubesphere/pkg/kapis/resources/v1alpha3/handler.go:155 +0xb0b
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).handleListResources(0xc0008c2460, 0xc001f934d0, 0xc00237d490)
	/home/runner/work/kubesphere/kubesphere/pkg/kapis/resources/v1alpha3/handler.go:97 +0x2cb
github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc001f934d0, 0xc00237d490)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:283 +0x3e
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001f93560, 0xc001f934d0, 0xc00237d490)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:21 +0x8b
kubesphere.io/kubesphere/pkg/apiserver.logRequestAndResponse(0xc001f934d0, 0xc00237d490, 0xc001f93560)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/apiserver.go:531 +0x82
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001f93560, 0xc001f934d0, 0xc00237d490)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:19 +0x65
github.com/emicklei/go-restful.(*Container).dispatch(0xc000707440, 0x38c1b80, 0xc00092b7a0, 0xc00244a800)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:285 +0x866
net/http.HandlerFunc.ServeHTTP(0xc0003f2950, 0x38c1b80, 0xc00092b7a0, 0xc00244a800)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0009140c0, 0x38c1b80, 0xc00092b7a0, 0xc00244a800)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2416 +0x1bd
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc000707440, 0x38c1b80, 0xc00092b7a0, 0xc00244a800)
	/home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:303 +0x4d
kubesphere.io/kubesphere/pkg/apiserver/filters.WithKubeAPIServer.func1(0x38c1b80, 0xc00092b7a0, 0xc00244a800)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/kubeapiserver.go:71 +0x37f
net/http.HandlerFunc.ServeHTTP(0xc000a22c00, 0x38c1b80, 0xc00092b7a0, 0xc00244a800)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x38c1b80, 0xc00092b7a0, 0xc00244a800)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authorization.go:50 +0x37c
net/http.HandlerFunc.ServeHTTP(0xc000a22c80, 0x38c1b80, 0xc00092b7a0, 0xc00244a800)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x38c1b80, 0xc00092b7a0, 0xc00244a600)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authentication.go:95 +0xb6b
net/http.HandlerFunc.ServeHTTP(0xc0000dc500, 0x38c1b80, 0xc00092b7a0, 0xc00244a600)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x38c1b80, 0xc00092b7a0, 0xc00244a500)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc000a37cb0, 0x38c1b80, 0xc00092b7a0, 0xc00244a500)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc00092a000, 0x38c1b80, 0xc00092b7a0, 0xc00244a500)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc0006ed0e0, 0x38d4780, 0xc0026cf180)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384
```

**k8s StorageClass**
```
[root@i-myi8en26 nfs]# kubectl get sc
NAME                  PROVISIONER      RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
hostpath (default)    hostpath         Delete          Immediate           false                  13m
managed-nfs-storage   fuseim.pri/ifs   Delete          Immediate           false                  9m27s
```

**nfs-storage**
refer: https://jimmysong.io/kubernetes-handbook/practice/using-nfs-for-persistent-storage.html

**hostpath**
refer: https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/storage-setup.yml

**Comment by cumirror** [comment]
This problem is because wrong pvc configuration missing storageClassName field.
After setting this field, the storage volume function of kubeSphere is ok. 

/close
