### ISSUE TITLE
self defined kubernetes agent pod template can not deploy yaml to kubernetes

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubesphere#2996]
## environment

kubesphere 3.0.0

demo github address: https://github.com/willzhang/spring-demo/blob/master/deploy/deployment.yaml

create an empty pipeline, and paste follow script
```groovy
pipeline {
  agent {
    kubernetes {
      yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: maven
    image: registry.cn-shenzhen.aliyuncs.com/images_mirror/maven:latest
    command:
    - cat
    tty: true
'''
      label 'default'
    }
  }

  environment {
      GIT_CREDENTIAL_ID = 'git-id'
      KUBECONFIG_CREDENTIAL_ID = 'demo-kubeconfig'
      NAMESPACE = 'demo-ns'
  }

  stages {
        stage('scm checkout') {
            steps {
                git(url: 'https://github.com.cnpmjs.org/willzhang/spring-demo.git', credentialsId: "$GIT_CREDENTIAL_ID", branch: 'master', changelog: true, poll: false)
            }
        }

        stage('deploy app') {
            steps {
                kubernetesDeploy(enableConfigSubstitution: true, deleteResource: true, kubeconfigId: "$KUBECONFIG_CREDENTIAL_ID", configs: 'deploy/deployment.yaml')
            }
        }
  }
}
```

the deployment.yaml file content is very simple ,and run kubectl apply by hand is success.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: demo
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: registry.cn-shenzhen.aliyuncs.com/images_mirror/nginx:latest
        ports:
        - containerPort: 80
```

but run pipeline will get error at the second stage:
```
Started by user demo-user
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
‘default-k2lmq-lxsdr’ is offline
Agent default-k2lmq-lxsdr is provisioned from template Kubernetes Pod Template
---
apiVersion: "v1"
kind: "Pod"
metadata:
  annotations:
    buildUrl: "http://ks-jenkins.kubesphere-devops-system:80/job/demo-cicd8qrtw/job/demo-pipeline3/13/"
  labels:
    app: "jenkins-agent"
    jenkins: "slave"
    jenkins/default: "true"
  name: "default-k2lmq-lxsdr"
spec:
  containers:
  - command:
    - "cat"
    image: "registry.cn-shenzhen.aliyuncs.com/images_mirror/maven:latest"
    name: "maven"
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "ks-jenkins-agent.kubesphere-devops-system:50000"
    - name: "JENKINS_AGENT_NAME"
      value: "default-k2lmq-lxsdr"
    - name: "JENKINS_NAME"
      value: "default-k2lmq-lxsdr"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "JENKINS_URL"
      value: "http://ks-jenkins.kubesphere-devops-system:80/"
    image: "jenkins/jnlp-slave:alpine"
    name: "jnlp"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  nodeSelector: {}
  restartPolicy: "Never"
  volumes:
  - emptyDir: {}
    name: "workspace-volume"

Running on default-k2lmq-lxsdr in /home/jenkins/agent/workspace/demo-cicd8qrtw/demo-pipeline3
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (scm checkout)
[Pipeline] git
using credential git-id
Cloning the remote Git repository
Cloning repository https://github.com.cnpmjs.org/willzhang/spring-demo.git
 > git init /home/jenkins/agent/workspace/demo-cicd8qrtw/demo-pipeline3 # timeout=10
Fetching upstream changes from https://github.com.cnpmjs.org/willzhang/spring-demo.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --force --progress https://github.com.cnpmjs.org/willzhang/spring-demo.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com.cnpmjs.org/willzhang/spring-demo.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com.cnpmjs.org/willzhang/spring-demo.git # timeout=10
Fetching upstream changes from https://github.com.cnpmjs.org/willzhang/spring-demo.git
using GIT_ASKPASS to set credentials 
 > git fetch --tags --force --progress https://github.com.cnpmjs.org/willzhang/spring-demo.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision a42a2a4f9328a555495f03ae544cb684dd1cd89c (refs/remotes/origin/master)
Commit message: "Update test.jenkinsfile"
First time build. Skipping changelog.
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy app)
[Pipeline] kubernetesDeploy
Starting Kubernetes deployment
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a42a2a4f9328a555495f03ae544cb684dd1cd89c
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b master a42a2a4f9328a555495f03ae544cb684dd1cd89c
Loading configuration: /home/jenkins/agent/workspace/demo-cicd8qrtw/demo-pipeline3/deploy/deployment.yaml
ERROR: ERROR: java.lang.RuntimeException: io.kubernetes.client.openapi.ApiException: java.net.SocketException: Broken pipe (Write failed)
hudson.remoting.ProxyException: java.lang.RuntimeException: io.kubernetes.client.openapi.ApiException: java.net.SocketException: Broken pipe (Write failed)
	at com.microsoft.jenkins.kubernetes.wrapper.ResourceManager.handleApiExceptionExceptNotFound(ResourceManager.java:180)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$DeploymentUpdater.deleteResource(V1ResourceManager.java:249)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$DeploymentUpdater.deleteResource(V1ResourceManager.java:201)
	at com.microsoft.jenkins.kubernetes.wrapper.ResourceManager$ResourceUpdater.delete(ResourceManager.java:108)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.handleResource(KubernetesClientWrapper.java:291)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:256)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:172)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:124)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:106)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 100.117.144.172/100.117.144.172:52858
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.FilePath.act(FilePath.java:1160)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:68)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
Caused by: hudson.remoting.ProxyException: io.kubernetes.client.openapi.ApiException: java.net.SocketException: Broken pipe (Write failed)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:898)
	at io.kubernetes.client.openapi.apis.AppsV1Api.deleteNamespacedDeploymentWithHttpInfo(AppsV1Api.java:2452)
	at io.kubernetes.client.openapi.apis.AppsV1Api.deleteNamespacedDeployment(AppsV1Api.java:2424)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$DeploymentUpdater.deleteResource(V1ResourceManager.java:246)
	... 16 more
Caused by: hudson.remoting.ProxyException: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:894)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:865)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
	at okhttp3.internal.http2.Http2Writer.windowUpdate(Http2Writer.java:244)
	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.java:502)
	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.java:489)
	at okhttp3.internal.connection.RealConnection.startHttp2(RealConnection.java:315)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:304)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:894)
	... 19 more
Api call failed with code 0, detailed message: null
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: Kubernetes deployment ended with HasError
Finished: FAILURE

```

**Comment by yuswift** [comment]
Please take a look at the following error:
`	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 100.117.144.172/100.117.144.172:52858
`

**Comment by LinuxSuRen** [comment]
It works in my KubeSphere cluster. I saw you also report this issue on the Jenkins plugin https://github.com/jenkinsci/kubernetes-cd-plugin/issues/122#issuecomment-697709124. So I would suggest we close this issue, and track it down from kubernetes-cd.

/kind support
