### ISSUE TITLE
External LDAP server authentication

### ISSUE THREAD

**Issue by Born2Bake** [kubesphere/kubesphere#3182]
Hey folks,

I am bit confused what's the right way to configure external LDAP server authentication?

What I did so far:

1. Configured ks-installer CRD in kubesphere console:

```
  name: ks-installer
  namespace: kubesphere-system
spec:
  alerting:
    enabled: false
  auditing:
    enabled: false
  authentication:
    authenticateRateLimiterDuration: 10m0s
    authenticateRateLimiterMaxTries: 10
    jwtSecret: ''
    loginHistoryRetentionPeriod: 168h
    maximumClockSkew: 10s
    multipleLogin: true
    oauthOptions:
      accessTokenInactivityTimeout: 30m
      accessTokenMaxAge: 1h
      identityProviders:
        - mappingMethod: auto
          name: ldap
          provider:
            host: '172.16.1.100:389'
            loginAttribute: uid
            mailAttribute: mail
            managerDN: 'cn=xxxxxxxx,dc=xxxxxxxxx,dc=xxx'
            managerPassword: xxxxxxxxxxxxxxxxxxxxx
            userSearchBase: 'ou=xxxxxxxxxx,dc=xxxxxxxx,dc=xxx'
          type: LDAPIdentityProvider
```

2. Found this topic https://kubesphere.com.cn/forum/d/2033-ga-ldap-oauth2/2 and edited cm kubesphere-config:

```
apiVersion: v1
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: 50
      authenticateRateLimiterDuration: 5m0s
      loginHistoryRetentionPeriod: 168h
      maximumClockSkew: 10s
      multipleLogin: True
      kubectlImage: kubesphere/kubectl:v1.0.0
      jwtSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      oauthOptions:
        accessTokenInactivityTimeout: 30m
        accessTokenMaxAge: 1h
        identityProviders:
          - mappingMethod: auto
            name: ldap
            provider:
              host: '172.16.1.100:389'
              loginAttribute: uid
              mailAttribute: mail
            managerDN: 'cn=xxxxxxxx,dc=xxxxxxxxx,dc=xxx'
            managerPassword: xxxxxxxxxxxxxxxxxxxxx
            userSearchBase: 'ou=xxxxxxxxxx,dc=xxxxxxxx,dc=xxx'
              type: LDAPIdentityProvider
    ldap:
      host: openldap.kubesphere-system.svc:389
      managerDN: cn=admin,dc=kubesphere,dc=io
      managerPassword: admin
      userSearchBase: ou=Users,dc=kubesphere,dc=io
      groupSearchBase: ou=Groups,dc=kubesphere,dc=io
```
However, I did not change default settings for ldap paragraph. I am wondering, if that one should be changed? If yes, will I be able to login with my default admin account which is out of external ldap server? Thank you

P.S. Logs from console when I am trying to login:

```
2020-12-05T03:18:02.868797316Z { UnauthorizedError: Not Login
2020-12-05T03:18:02.868831738Z     at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
2020-12-05T03:18:02.868855145Z     at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
2020-12-05T03:18:02.868874449Z     at renderView (/opt/kubesphere/console/server/server.js:23231:46)
2020-12-05T03:18:02.868894630Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:02.868910390Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:02.868920019Z     at /opt/kubesphere/console/server/server.js:70183:16
2020-12-05T03:18:02.868930780Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:02.868947113Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:02.868964124Z     at /opt/kubesphere/console/server/server.js:77986:37
2020-12-05T03:18:02.868981185Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:02.868998614Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:02.869014385Z     at /opt/kubesphere/console/server/server.js:70183:16
2020-12-05T03:18:02.869023985Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:02.869032563Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:02.869040793Z     at /opt/kubesphere/console/server/server.js:77986:37
2020-12-05T03:18:02.869055583Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
2020-12-05T03:18:02.870011826Z   --> GET / 302 2ms 43b 2020/12/05T03:18:02.869
2020-12-05T03:18:02.871600969Z   <-- GET /login 2020/12/05T03:18:02.871
2020-12-05T03:18:02.883540123Z   --> GET /login 200 13ms 14.82kb 2020/12/05T03:18:02.883
2020-12-05T03:18:12.867813462Z   <-- GET / 2020/12/05T03:18:12.867
2020-12-05T03:18:12.869596621Z { UnauthorizedError: Not Login
2020-12-05T03:18:12.869618279Z     at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
2020-12-05T03:18:12.869630127Z     at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
2020-12-05T03:18:12.869639281Z     at renderView (/opt/kubesphere/console/server/server.js:23231:46)
2020-12-05T03:18:12.869648169Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:12.869657276Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:12.869668433Z     at /opt/kubesphere/console/server/server.js:70183:16
2020-12-05T03:18:12.869678603Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:12.869687487Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:12.869696244Z     at /opt/kubesphere/console/server/server.js:77986:37
2020-12-05T03:18:12.869722285Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:12.869732405Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:12.869741409Z     at /opt/kubesphere/console/server/server.js:70183:16
2020-12-05T03:18:12.869750456Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:12.869759348Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:12.869768273Z     at /opt/kubesphere/console/server/server.js:77986:37
2020-12-05T03:18:12.869777572Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
2020-12-05T03:18:12.870360348Z   --> GET / 302 3ms 43b 2020/12/05T03:18:12.870
2020-12-05T03:18:12.871182928Z   <-- GET /login 2020/12/05T03:18:12.870
2020-12-05T03:18:12.883033954Z   --> GET /login 200 12ms 14.82kb 2020/12/05T03:18:12.882
2020-12-05T03:18:22.868273239Z   <-- GET / 2020/12/05T03:18:22.867
2020-12-05T03:18:22.869236773Z { UnauthorizedError: Not Login
2020-12-05T03:18:22.869270694Z     at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
2020-12-05T03:18:22.869295182Z     at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
2020-12-05T03:18:22.869315344Z     at renderView (/opt/kubesphere/console/server/server.js:23231:46)
2020-12-05T03:18:22.869335862Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:22.869358938Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:22.869379773Z     at /opt/kubesphere/console/server/server.js:70183:16
2020-12-05T03:18:22.869402828Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:22.869421982Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:22.869443356Z     at /opt/kubesphere/console/server/server.js:77986:37
2020-12-05T03:18:22.869461897Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:22.869479429Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:22.869489163Z     at /opt/kubesphere/console/server/server.js:70183:16
2020-12-05T03:18:22.869498631Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
2020-12-05T03:18:22.869508093Z     at next (/opt/kubesphere/console/server/server.js:6871:18)
2020-12-05T03:18:22.869517586Z     at /opt/kubesphere/console/server/server.js:77986:37
2020-12-05T03:18:22.869526973Z     at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
2020-12-05T03:18:22.869992987Z   --> GET / 302 2ms 43b 2020/12/05T03:18:22.869
2020-12-05T03:18:22.870689281Z   <-- GET /login 2020/12/05T03:18:22.870
2020-12-05T03:18:22.881313699Z   --> GET /login 200 10ms 14.82kb 2020/12/05T03:18:22.881
```

**Comment by wansir** [comment]
@Born2Bake https://kubesphere.io/docs/access-control-and-account-management/configuring-authentication/, after you configure the LDAP identity provider, you can still login with the default admin account.

**Comment by Born2Bake** [comment]
> @Born2Bake https://kubesphere.io/docs/access-control-and-account-management/configuring-authentication/, after you configure the LDAP identity provider, you can still login with the default admin account.

Can someone confirm that its working for them cause I ve changed oauth in configmap and I still cant use my openldap server to login?

**Comment by wansir** [comment]
@Born2Bake Don't forget to restart ks-apiserver. If you still can't log in, please pay attention to the error prompt when logging in.

**Comment by RolandMa1986** [comment]
Hi @Born2Bake, have you configured your kubesphere with LDAP successfully?
/kind support
/area iam
