### ISSUE TITLE
alerting-watcher start failed

### ISSUE THREAD

**Issue by charnet1019** [kubesphere/kubesphere#3266]
Kubesphere version: 2.1.1

The service alerting-watcher can not start after server reboot.

err log: 
[root@node2 opt]# kubectl logs -n kubesphere-alerting-system  alerting-watcher-799475d5dc-b2997 
2021-01-11 15:33:05.33919 -INFO- LoadConf: &{Log:{Level:info} Grpc:{ShowErrorCause:false} Mysql:{Host:mysql.kubesphere-system.svc Port:3306 User:root Password:password Database:alert Disable:false LogMode:false} Etcd:{Endpoints:etcd.kubesphere-system.svc:2379} Queue:{Type:redis Addr:redis://redis.kubesphere-system.svc:6379} App:{Host:localhost Port:9201 ApiHost:localhost ApiPort:9200 NotificationHost:notification.kubesphere-notification-system.svc:9201 RunMode:watcher AdapterPort:8080}} (config.go:108)
2021-01-11 15:33:05.33985 -INFO- mString:{"connStr":"redis://redis.kubesphere-system.svc:6379"} (redis.go:80)
2021-01-11 15:33:05.34044 -INFO- LoadConf: &{Log:{Level:info} Grpc:{ShowErrorCause:false} Mysql:{Host:mysql.kubesphere-system.svc Port:3306 User:root Password:password Database:alert Disable:false LogMode:false} Etcd:{Endpoints:etcd.kubesphere-system.svc:2379} Queue:{Type:redis Addr:redis://redis.kubesphere-system.svc:6379} App:{Host:localhost Port:9201 ApiHost:localhost ApiPort:9200 NotificationHost:notification.kubesphere-notification-system.svc:9201 RunMode:watcher AdapterPort:8080}} (config.go:108)
2021-01-11 15:33:10.35597 -CRITICAL- Failed to connect etcd... (global.go:77)
panic: context deadline exceeded

goroutine 1 [running]:
kubesphere.io/alert/pkg/global.(*GlobalCfg).openEtcd(0xc0003b5180, 0xc0003b5180)
        /go/src/kubesphere.io/alert/pkg/global/global.go:78 +0x24e
kubesphere.io/alert/pkg/global.newGlobalCfg(0xc00023bd90)
        /go/src/kubesphere.io/alert/pkg/global/global.go:44 +0x89
kubesphere.io/alert/pkg/global.GetInstance.func1()
        /go/src/kubesphere.io/alert/pkg/global/global.go:33 +0x22
sync.(*Once).Do(0x2b84528, 0x1b5beb0)
        /usr/local/go/src/sync/once.go:44 +0xb3
kubesphere.io/alert/pkg/global.GetInstance(0x203000)
        /go/src/kubesphere.io/alert/pkg/global/global.go:32 +0x39
kubesphere.io/alert/pkg/services/watcher.(*ExecutorWatcher).initExecutors(0xc000416a50, 0xc0003f6540, 0xc000416840)
        /go/src/kubesphere.io/alert/pkg/services/watcher/executor_watcher.go:103 +0x46
kubesphere.io/alert/pkg/services/watcher.(*ExecutorWatcher).Serve(0xc000416a50)
        /go/src/kubesphere.io/alert/pkg/services/watcher/executor_watcher.go:170 +0x2b
main.mainFuncWatcher()
        /go/src/kubesphere.io/alert/cmd/alert/main.go:73 +0x27
main.main()
        /go/src/kubesphere.io/alert/cmd/alert/main.go:92 +0x111

**Comment by wansir** [comment]
@charnet1019 

> 2021-01-11 15:33:10.35597 -CRITICAL- Failed to connect etcd... (global.go:77)

The error is caused cannot connect to etcd, please check the service status of `etcd.kubesphere-system.svc`.
