### ISSUE TITLE
ks-controller-manager always panic

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubesphere#3290]
**Describe the Bug**
ks-controller-manager always panic.

**Versions Used**
KubeSphere: v3.0.0

**Environment**
This issue is not related to the environment.

**How To Reproduce**
1. Go to DevOps project
2. Create a Pipeline with choice parameters
3. Trigger the Pipeline, then wait for a while
4. Update the Pipeline again

You will find out the `ks-contrller-manager` just keep panic forever. Please pay attention on this line: `pkg/simple/client/devops/jenkins/pipeline_internal.go:234`

See the full stack of panic:
```
goroutine 1063 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1f0b740, 0x393d920)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
github.com/beevik/etree.(*Element).SelectElements(0x0, 0x22721e6, 0x6, 0x0, 0xc00016b178, 0x3992e80)
	/home/runner/go/pkg/mod/github.com/beevik/etree@v1.1.0/etree.go:759 +0x69
kubesphere.io/kubesphere/pkg/simple/client/devops/jenkins.getParametersfromEtree(0xc002159b00, 0xc001a89e20, 0x2, 0xc002159c80)
	/home/runner/work/kubesphere/kubesphere/pkg/simple/client/devops/jenkins/pipeline_internal.go:234 +0x55a
kubesphere.io/kubesphere/pkg/simple/client/devops/jenkins.parsePipelineConfigXml(0xc00107aa00, 0x1463, 0x1463, 0x0, 0x0)
	/home/runner/work/kubesphere/kubesphere/pkg/simple/client/devops/jenkins/pipeline_internal.go:131 +0x20c
kubesphere.io/kubesphere/pkg/simple/client/devops/jenkins.(*Jenkins).GetProjectPipelineConfig(0xc0006fcb10, 0xc0013b9e40, 0x9, 0xc0013b9b80, 0x6, 0x1, 0x0, 0x1)
	/home/runner/work/kubesphere/kubesphere/pkg/simple/client/devops/jenkins/project_pipeline.go:154 +0x696
kubesphere.io/kubesphere/pkg/controller/pipeline.(*Controller).syncHandler(0xc000641360, 0xc0013b9e40, 0x10, 0xc000c96750, 0xc000d63cf0)
	/home/runner/work/kubesphere/kubesphere/pkg/controller/pipeline/pipeline_controller.go:234 +0x707
kubesphere.io/kubesphere/pkg/controller/pipeline.(*Controller).processNextWorkItem.func1(0xc000641360, 0x1e39320, 0xc000e29350, 0x0, 0x0)
	/home/runner/work/kubesphere/kubesphere/pkg/controller/pipeline/pipeline_controller.go:143 +0xf3
kubesphere.io/kubesphere/pkg/controller/pipeline.(*Controller).processNextWorkItem(0xc000641360, 0x1)
	/home/runner/work/kubesphere/kubesphere/pkg/controller/pipeline/pipeline_controller.go:150 +0x51
kubesphere.io/kubesphere/pkg/controller/pipeline.(*Controller).worker(0xc000641360)
	/home/runner/work/kubesphere/kubesphere/pkg/controller/pipeline/pipeline_controller.go:163 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000f27220)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f27220, 0x3b9aca00, 0x0, 0x1, 0xc000412ae0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000f27220, 0x3b9aca00, 0xc000412ae0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:88 +0x4d
created by kubesphere.io/kubesphere/pkg/controller/pipeline.(*Controller).Run
	/home/runner/work/kubesphere/kubesphere/pkg/controller/pipeline/pipeline_controller.go:183 +0x23f
```

**Expected behavior**
Any kind of Pipeline does not affect any components of KubeSphere.

/kind bug
/area devops

**Comment by LinuxSuRen** [comment]
There's another issue #3176 that is very similar to this.
