### ISSUE TITLE
devops system could not start the pipeline, the pipeline is always in the queue.

### ISSUE THREAD

**Issue by david0718** [kubesphere/kubesphere#3361]
**Describe the Bug**

The base-xxx pod could not be started. Its' status is ContainerCreating, and then disappears.

below is the jenkins docker logs

Thanks very much.

____________________________________________________________________________________________

2021-02-18T16:29:35.394184681+08:00 WARNING: Error in provisioning; agent=KubernetesSlave name: base-mmrhl, template=PodTemplate{, name='base', namespace='kubesphere-devops-system', label='base', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock], HostPathVolume [mountPath=/root/.sonar/cache, hostPath=sonar_cache]], containers=[ContainerTemplate{name='base', image='kubesphere/builder-base:v2.1.0', command='cat', args='', ttyEnabled=true, resourceRequestCpu='100m', resourceRequestMemory='100Mi', resourceLimitCpu='4000m', resourceLimitMemory='8192Mi'}, ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', command='jenkins-slave', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='50m', resourceRequestMemory='400Mi', resourceLimitMemory='1536Mi'}]}

2021-02-18T16:29:35.394197989+08:00 io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [100000] milliseconds for [Pod] with name:[base-mmrhl] in namespace [kubesphere-devops-system].

2021-02-18T16:29:35.394205947+08:00 at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.await(AllContainersRunningPodWatcher.java:130)

2021-02-18T16:29:35.394214062+08:00 at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:134)

2021-02-18T16:29:35.394220015+08:00 at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)

2021-02-18T16:29:35.394227194+08:00 at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)

2021-02-18T16:29:35.394232801+08:00 at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)

2021-02-18T16:29:35.394238189+08:00 at java.util.concurrent.FutureTask.run(FutureTask.java:266)

2021-02-18T16:29:35.394243523+08:00 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

2021-02-18T16:29:35.394249754+08:00 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

2021-02-18T16:29:35.394256584+08:00 at java.lang.Thread.run(Thread.java:748)

2021-02-18T16:29:35.394262483+08:00

2021-02-18T16:29:35.395343666+08:00 Feb 18, 2021 8:29:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate

2021-02-18T16:29:35.395375357+08:00 INFO: Terminating Kubernetes instance for agent base-mmrhl

2021-02-18T16:29:35.431135835+08:00 Feb 18, 2021 8:29:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod

2021-02-18T16:29:35.431181649+08:00 INFO: Terminated Kubernetes instance for agent kubesphere-devops-system/base-mmrhl

2021-02-18T16:29:35.431310056+08:00 Terminated Kubernetes instance for agent kubesphere-devops-system/base-mmrhl

2021-02-18T16:29:35.431322305+08:00 Disconnected computer base-mmrhl

2021-02-18T16:29:35.431338077+08:00 Feb 18, 2021 8:29:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate

2021-02-18T16:29:35.431354510+08:00 INFO: Disconnected computer base-mmrhl

2021-02-18T16:29:40.246312653+08:00 Feb 18, 2021 8:29:40 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision

2021-02-18T16:29:40.246374107+08:00 INFO: Excess workload after pending Kubernetes agents: 1

2021-02-18T16:29:40.246392223+08:00 Feb 18, 2021 8:29:40 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision

2021-02-18T16:29:40.246398886+08:00 INFO: Template for label null: Kubernetes Pod Template

2021-02-18T16:29:45.258452800+08:00 Feb 18, 2021 8:29:45 AM hudson.slaves.NodeProvisioner$2 run

2021-02-18T16:29:45.258511767+08:00 INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)

2021-02-18T16:29:45.303269396+08:00 Feb 18, 2021 8:29:45 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch

2021-02-18T16:29:45.303317292+08:00 INFO: Created Pod: kubesphere-devops-system/base-p246k

2021-02-18T16:29:45.359611391+08:00 Feb 18, 2021 8:29:45 AM okhttp3.internal.platform.Platform log

2021-02-18T16:29:45.359776732+08:00 INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by LinuxSuRen** [comment]
Please check the log of Jenkins builder pod. I didn't get useful info from above.

/kind support
/area devops

**Comment by david0718** [comment]
I checked the log for Jenkins pod, it repeat to create the pod, but always failed. As below.  Not sure if it is useful or not.

____________________________________________________________________________________________________


WARNING: Plugin Step 1 ,admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidWlkIjoiMGZlYWIwZjQtZTY1Zi00ZTk5LWI5ZjUtNmFiYTg4NDQ2NDJjIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTYxMzY0NDAzMSwiaWF0IjoxNjEzNjM2ODMxLCJpc3MiOiJrdWJlc3BoZXJlIiwibmJmIjoxNjEzNjM2ODMxfQ.6XNkSF2kVLjT1z3Osqd1MrwCn03UwENWFjnS5ZmL3Sc
Feb 18, 2021 8:51:31 AM io.kubesphere.jenkins.devops.auth.KubesphereApiTokenAuthenticator authenticate
WARNING: Plugin Step 2 ,admin,[Lorg.acegisecurity.GrantedAuthority;@3f6e47ac
Feb 18, 2021 8:51:35 AM io.kubesphere.jenkins.devops.auth.KubesphereApiTokenAuthenticator authenticate
WARNING: Plugin Step 1 ,admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidWlkIjoiMGZlYWIwZjQtZTY1Zi00ZTk5LWI5ZjUtNmFiYTg4NDQ2NDJjIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTYxMzY0NDAzMSwiaWF0IjoxNjEzNjM2ODMxLCJpc3MiOiJrdWJlc3BoZXJlIiwibmJmIjoxNjEzNjM2ODMxfQ.6XNkSF2kVLjT1z3Osqd1MrwCn03UwENWFjnS5ZmL3Sc
Feb 18, 2021 8:51:35 AM io.kubesphere.jenkins.devops.auth.KubesphereApiTokenAuthenticator authenticate
WARNING: Plugin Step 2 ,admin,[Lorg.acegisecurity.GrantedAuthority;@50a76d18
Feb 18, 2021 8:51:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: base-6vqvl, template=PodTemplate{, name='base', namespace='kubesphere-devops-system', label='base', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock], HostPathVolume [mountPath=/root/.sonar/cache, hostPath=sonar_cache]], containers=[ContainerTemplate{name='base', image='kubesphere/builder-base:v2.1.0', command='cat', args='', ttyEnabled=true, resourceRequestCpu='100m', resourceRequestMemory='100Mi', resourceLimitCpu='4000m', resourceLimitMemory='8192Mi'}, ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', command='jenkins-slave', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='50m', resourceRequestMemory='400Mi', resourceLimitMemory='1536Mi'}]}
java.lang.IllegalStateException: Pod has terminated containers: kubesphere-devops-system/base-6vqvl (base, jnlp)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:166)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:187)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.await(AllContainersRunningPodWatcher.java:127)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:134)
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Feb 18, 2021 8:51:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent base-6vqvl
Feb 18, 2021 8:51:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: base-6412q, template=PodTemplate{, name='base', namespace='kubesphere-devops-system', label='base', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock], HostPathVolume [mountPath=/root/.sonar/cache, hostPath=sonar_cache]], containers=[ContainerTemplate{name='base', image='kubesphere/builder-base:v2.1.0', command='cat', args='', ttyEnabled=true, resourceRequestCpu='100m', resourceRequestMemory='100Mi', resourceLimitCpu='4000m', resourceLimitMemory='8192Mi'}, ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', command='jenkins-slave', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='50m', resourceRequestMemory='400Mi', resourceLimitMemory='1536Mi'}]}
java.lang.IllegalStateException: Pod has terminated containers: kubesphere-devops-system/base-6412q (base, jnlp)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:166)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:187)
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.await(AllContainersRunningPodWatcher.java:127)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:134)
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)Error in provisioning; agent=KubernetesSlave name: base-6vqvl, template=PodTemplate{, name='base', 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Feb 18, 2021 8:51:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent base-6412q
Feb 18, 2021 8:51:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod
INFO: Terminated Kubernetes instance for agent kubesphere-devops-system/base-6412q
Terminated Kubernetes instance for agent kubesphere-devops-system/base-6412q
Disconnected computer base-6412q
Feb 18, 2021 8:51:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Disconnected computer base-6412q
Feb 18, 2021 8:51:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod
INFO: Terminated Kubernetes instance for agent kubesphere-devops-system/base-6vqvl
Terminated Kubernetes instance for agent kubesphere-devops-system/base-6vqvl
Disconnected computer base-6vqvl
Feb 18, 2021 8:51:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Disconnected computer base-6vqvl
Feb 18, 2021 8:51:39 AM io.kubesphere.jenkins.devops.auth.KubesphereApiTokenAuthenticator authenticate
WARNING: Plugin Step 1 ,admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidWlkIjoiMGZlYWIwZjQtZTY1Zi00ZTk5LWI5ZjUtNmFiYTg4NDQ2NDJjIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTYxMzY0NDAzMSwiaWF0IjoxNjEzNjM2ODMxLCJpc3MiOiJrdWJlc3BoZXJlIiwibmJmIjoxNjEzNjM2ODMxfQ.6XNkSF2kVLjT1z3Osqd1MrwCn03UwENWFjnS5ZmL3Sc
Feb 18, 2021 8:51:39 AM io.kubesphere.jenkins.devops.auth.KubesphereApiTokenAuthenticator authenticate
WARNING: Plugin Step 2 ,admin,[Lorg.acegisecurity.GrantedAuthority;@39a6bc13
Feb 18, 2021 8:51:40 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Kubernetes agents: 2
Feb 18, 2021 8:51:40 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Template for label null: Kubernetes Pod Template
Feb 18, 2021 8:51:43 AM io.kubesphere.jenkins.devops.auth.KubesphereApiTokenAuthenticator authenticate
WARNING: Plugin Step 1 ,admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidWlkIjoiMGZlYWIwZjQtZTY1Zi0

**Comment by LinuxSuRen** [comment]
Again, you need to check the log of `base-xxx`.

**Comment by david0718** [comment]
ahaa, after I input the command for the base-xxx log, the pod has already been removed by the system. :((

**Comment by LinuxSuRen** [comment]
This is the only way. You might need to be faster.

**Comment by david0718** [comment]
I  installed 3.0 in another  k8s cluster. The same issue occurs.

**Comment by LinuxSuRen** [comment]
It's not necessary to install a new cluster. The only way is to get the log output of the pod. You can write a small shell script to get it. I know it's not easy due to it might disappear very fast.

**Comment by david0718** [comment]
HI SuRen
How are you?

After days’ thinking and practice.
1)my k8s use containerd as the image part.
2)logs found as below for maven image


异常 | Failed | 1秒 | kubelet | Error:  failed to create containerd task: OCI runtime create failed:  container_linux.go:367: starting container process caused:  process_linux.go:495: container init caused: rootfs_linux.go:60:  mounting  "/run/containerd/io.containerd.runtime.v1.linux/k8s.io/jnlp/jenkins_maven_cache"  to rootfs at "/root/.m2" caused: stat  /run/containerd/io.containerd.runtime.v1.linux/k8s.io/jnlp/jenkins_maven_cache:  no such file or directory: unknown
-- | -- | -- | -- | --

Hope this could be helpful.

Thanks
David

**Comment by LinuxSuRen** [comment]
The problem might be caused by the volume path. Try to provide an absolute path instead related path. For example, change `jenkins_maven_cache` to `/var/data/jenkins_maven_cache`.

![image](https://user-images.githubusercontent.com/1450685/111937439-b488ed00-8b02-11eb-8373-64585d191ba7.png)

I'm not sure if it works.

**Comment by david0718** [comment]
Hi SuRen
I checked my jenkins -> Config System-> Cloud:  sonar cache and maven cache folder as you mentioned. The problem are solved.

Thanks a lot.
David

**Comment by LinuxSuRen** [comment]
Glad helped you.
/close
