### ISSUE TITLE
Bookinfo example not working correctly

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3554]
**Describe the Bug**

After I update the rating component to `examples-bookinfo-ratings-v2:1.13.0`, I encountered the following error

![image](https://user-images.githubusercontent.com/8263040/112103612-f8ecb980-8be4-11eb-9350-e061e5c96621.png)

![image](https://user-images.githubusercontent.com/8263040/112103910-6bf63000-8be5-11eb-8616-c7fc3b6d4bb5.png)

```
kubectl -n nginx logs ratings-ratingv2-5f4b99c5d7-gxw22 ratings
GET /ratings/0
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at module.exports (/opt/microservices/node_modules/mongodb/lib/url_parser.js:13:23)
    at connect (/opt/microservices/node_modules/mongodb/lib/mongo_client.js:485:3)
    at Function.MongoClient.connect (/opt/microservices/node_modules/mongodb/lib/mongo_client.js:250:3)
    at /opt/microservices/ratings.js:112:19
    at /opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:130:3
    at HttpChain.next (/opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:123:9)
    at HttpDispatcher.doDispatch (/opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:58:13)
GET /ratings/0
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at module.exports (/opt/microservices/node_modules/mongodb/lib/url_parser.js:13:23)
    at connect (/opt/microservices/node_modules/mongodb/lib/mongo_client.js:485:3)
    at Function.MongoClient.connect (/opt/microservices/node_modules/mongodb/lib/mongo_client.js:250:3)
    at /opt/microservices/ratings.js:112:19
    at /opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:130:3
    at HttpChain.next (/opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:123:9)
    at HttpDispatcher.doDispatch (/opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:58:13)
```

/kind bug

**Comment by wansir** [comment]
verified

/close
