### ISSUE TITLE
Unable to access dashboard

### ISSUE THREAD

**Issue by LLLLimbo** [kubesphere/kubesphere#4138]
*Unable to access dashboard*

**Environment: OS & Hardware Information**

- Host
  - System: Microsoft Windows 11 Home
  - Version: 10.0.22000
- Docker Desktop
  - Version: 3.5.2
- Kubernetes
  - Version: V1.21.2
  - Number of Node: 1
- Kubesphere
  - Version: v3.1.0

Hardware:

- 16C/32G

**Error logs *

When I try to access the dashboard, I get the following error.

`ks-console` logs

```bash
FetchError: request to http://ks-apiserver.kubesphere-system.svc/kapis/version failed, reason: connect ECONNREFUSED 10.105.128.232:80
    at ClientRequest.<anonymous> (/opt/kubesphere/console/server/server.js:47886:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```

**Comment by RolandMa1986** [comment]
@LLLLimbo 
We haven't test KubeSphere on **Docker Desktop** yet. And may not officially support it. Please try to run KubeSphere in Minikube or Ubuntu/Centos-based VM.
