### ISSUE TITLE
ks-apiserver may crash because of concurrent map read and map write

### ISSUE THREAD

**Issue by xushuxun** [kubesphere/kubesphere#4357]
**Describe the Bug**
ks-apiserver may crash

Here is the panic goroutine stack:
```
fatal error: concurrent map read and map write

goroutine 1764 [running]:
runtime.throw(0x34a39a6, 0x21)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc001e3e218 sp=0xc001e3e1e8 pc=0x438072
runtime.mapaccess2(0x2f82040, 0xc0015bc660, 0xc000a25410, 0xc000a25410, 0xc002a802df)
        /usr/local/go/src/runtime/map.go:469 +0x255 fp=0xc001e3e258 sp=0xc001e3e218 pc=0x40f675
reflect.mapaccess(0x2f82040, 0xc0015bc660, 0xc000a25410, 0x3485d1b)
        /usr/local/go/src/runtime/map.go:1318 +0x3f fp=0xc001e3e290 sp=0xc001e3e258 pc=0x46837f
reflect.Value.MapIndex(0x2f82040, 0xc0000383b8, 0x195, 0x2e41080, 0xc000a25410, 0x98, 0x2e41080, 0xc000a254e0, 0x98)
        /usr/local/go/src/reflect/value.go:1189 +0x16e fp=0xc001e3e308 sp=0xc001e3e290 pc=0x4a02ee
encoding/json.mapEncoder.encode(0x3580f88, 0xc002050700, 0x2f82040, 0xc0000383b8, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:813 +0x317 fp=0xc001e3e4b0 sp=0xc001e3e308 pc=0x5d1ff7
encoding/json.mapEncoder.encode-fm(0xc002050700, 0x2f82040, 0xc0000383b8, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:779 +0x6d fp=0xc001e3e4f0 sp=0xc001e3e4b0 pc=0x5de74d
encoding/json.structEncoder.encode(0xc001c4e000, 0x10, 0x10, 0xc00225b4a0, 0xc002050700, 0x33ac260, 0xc000038320, 0x199, 0x100)
        /usr/local/go/src/encoding/json/encode.go:761 +0x2ab fp=0xc001e3e588 sp=0xc001e3e4f0 pc=0x5d1a8b
encoding/json.structEncoder.encode-fm(0xc002050700, 0x33ac260, 0xc000038320, 0x199, 0x100)
        /usr/local/go/src/encoding/json/encode.go:732 +0x8c fp=0xc001e3e5e0 sp=0xc001e3e588 pc=0x5de6ac
encoding/json.structEncoder.encode(0xc000a29b00, 0x5, 0x8, 0xc001812750, 0xc002050700, 0x31f02e0, 0xc000038300, 0x199, 0x2f70100)
        /usr/local/go/src/encoding/json/encode.go:761 +0x2ab fp=0xc001e3e678 sp=0xc001e3e5e0 pc=0x5d1a8b
encoding/json.structEncoder.encode-fm(0xc002050700, 0x31f02e0, 0xc000038300, 0x199, 0xc000030100)
        /usr/local/go/src/encoding/json/encode.go:732 +0x8c fp=0xc001e3e6d0 sp=0xc001e3e678 pc=0x5de6ac
encoding/json.ptrEncoder.encode(0xc001812780, 0xc002050700, 0x3425cc0, 0xc000038300, 0x16, 0x3420100)
        /usr/local/go/src/encoding/json/encode.go:944 +0x125 fp=0xc001e3e790 sp=0xc001e3e6d0 pc=0x5d3805
encoding/json.ptrEncoder.encode-fm(0xc002050700, 0x3425cc0, 0xc000038300, 0x16, 0xc000030100)
        /usr/local/go/src/encoding/json/encode.go:929 +0x6d fp=0xc001e3e7d0 sp=0xc001e3e790 pc=0x5de92d
encoding/json.(*encodeState).reflectValue(0xc002050700, 0x3425cc0, 0xc000038300, 0x16, 0xc000030100)
        /usr/local/go/src/encoding/json/encode.go:360 +0x82 fp=0xc001e3e808 sp=0xc001e3e7d0 pc=0x5cf102
encoding/json.interfaceEncoder(0xc002050700, 0x2f2a7c0, 0xc000a25160, 0x194, 0x2f20100)
        /usr/local/go/src/encoding/json/encode.go:716 +0xac fp=0xc001e3e850 sp=0xc001e3e808 pc=0x5d15ec
encoding/json.arrayEncoder.encode(0x3580e70, 0xc002050700, 0x2db2e40, 0xc00239e0c0, 0x197, 0x100)
        /usr/local/go/src/encoding/json/encode.go:915 +0xd6 fp=0xc001e3e8a8 sp=0xc001e3e850 pc=0x5d35b6
encoding/json.arrayEncoder.encode-fm(0xc002050700, 0x2db2e40, 0xc00239e0c0, 0x197, 0x100)
        /usr/local/go/src/encoding/json/encode.go:908 +0x6d fp=0xc001e3e8e8 sp=0xc001e3e8a8 pc=0x5de88d
encoding/json.sliceEncoder.encode(0xc000456620, 0xc002050700, 0x2db2e40, 0xc00239e0c0, 0x197, 0x100)
        /usr/local/go/src/encoding/json/encode.go:888 +0xfe fp=0xc001e3e9e0 sp=0xc001e3e8e8 pc=0x5d2e1e
encoding/json.sliceEncoder.encode-fm(0xc002050700, 0x2db2e40, 0xc00239e0c0, 0x197, 0x100)
        /usr/local/go/src/encoding/json/encode.go:868 +0x6d fp=0xc001e3ea20 sp=0xc001e3e9e0 pc=0x5de7ed
encoding/json.structEncoder.encode(0xc001d3fd40, 0x2, 0x2, 0xc001d41110, 0xc002050700, 0x30d5520, 0xc00239e0c0, 0x199, 0x2f70100)
        /usr/local/go/src/encoding/json/encode.go:761 +0x2ab fp=0xc001e3eab8 sp=0xc001e3ea20 pc=0x5d1a8b
encoding/json.structEncoder.encode-fm(0xc002050700, 0x30d5520, 0xc00239e0c0, 0x199, 0xc002390100)
        /usr/local/go/src/encoding/json/encode.go:732 +0x8c fp=0xc001e3eb10 sp=0xc001e3eab8 pc=0x5de6ac
encoding/json.ptrEncoder.encode(0xc001d41140, 0xc002050700, 0x2d73980, 0xc00239e0c0, 0x16, 0x2d70100)
        /usr/local/go/src/encoding/json/encode.go:944 +0x125 fp=0xc001e3ebd0 sp=0xc001e3eb10 pc=0x5d3805
encoding/json.ptrEncoder.encode-fm(0xc002050700, 0x2d73980, 0xc00239e0c0, 0x16, 0x5260100)
        /usr/local/go/src/encoding/json/encode.go:929 +0x6d fp=0xc001e3ec10 sp=0xc001e3ebd0 pc=0x5de92d
encoding/json.(*encodeState).reflectValue(0xc002050700, 0x2d73980, 0xc00239e0c0, 0x16, 0xc001e30100)
        /usr/local/go/src/encoding/json/encode.go:360 +0x82 fp=0xc001e3ec48 sp=0xc001e3ec10 pc=0x5cf102
encoding/json.(*encodeState).marshal(0xc002050700, 0x2d73980, 0xc00239e0c0, 0x100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:332 +0xf9 fp=0xc001e3eca8 sp=0xc001e3ec48 pc=0x5cecf9
encoding/json.Marshal(0x2d73980, 0xc00239e0c0, 0xc000598588, 0xc0002909f0, 0x3474b0c, 0x10, 0xc0000cd828)
        /usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc001e3ed20 sp=0xc001e3eca8 pc=0x5ce172
encoding/json.MarshalIndent(0x2d73980, 0xc00239e0c0, 0x0, 0x0, 0x3969948, 0x1, 0xc000038300, 0xc000fceca8, 0xc000598588, 0x358a578, ...)
        /usr/local/go/src/encoding/json/encode.go:176 +0x3f fp=0xc001e3eda8 sp=0xc001e3ed20 pc=0x5ce31f
github.com/emicklei/go-restful.writeJSON(0xc00085f1f0, 0xc8, 0x3474b0c, 0x10, 0x2d73980, 0xc00239e0c0, 0xc002cac255, 0xc00123b8a8)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/entity_accessors.go:149 +0x95 fp=0xc001e3ee50 sp=0xc001e3eda8 pc=0x12d93b5
github.com/emicklei/go-restful.entityJSONAccess.Write(...)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/entity_accessors.go:137
github.com/emicklei/go-restful.(*entityJSONAccess).Write(0xc0004d0670, 0xc00085f1f0, 0xc8, 0x2d73980, 0xc00239e0c0, 0x0, 0x0)
        <autogenerated>:1 +0x71 fp=0xc001e3eea0 sp=0xc001e3ee50 pc=0x12e5cb1
github.com/emicklei/go-restful.(*Response).WriteHeaderAndEntity(0xc00085f1f0, 0xc8, 0x2d73980, 0xc00239e0c0, 0x0, 0xc00258b380)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/response.go:144 +0x74 fp=0xc001e3eee8 sp=0xc001e3eea0 pc=0x12de2b4
github.com/emicklei/go-restful.(*Response).WriteEntity(...)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/response.go:128
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).handleListResources(0xc000c1c760, 0xc001241500, 0xc00085f1f0)
        /workspace/pkg/kapis/resources/v1alpha3/handler.go:90 +0x4e5 fp=0xc001e3efc8 sp=0xc001e3eee8 pc=0x24f0285
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).handleListResources-fm(0xc001241500, 0xc00085f1f0)
        /workspace/pkg/kapis/resources/v1alpha3/handler.go:83 +0x47 fp=0xc001e3eff0 sp=0xc001e3efc8 pc=0x24f4de7
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001241590, 0xc001241500, 0xc00085f1f0)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/filter.go:21 +0x8c fp=0xc001e3f018 sp=0xc001e3eff0 pc=0x12d986c
kubesphere.io/kubesphere/pkg/apiserver.monitorRequest(0xc001241500, 0xc00085f1f0, 0xc001241590)
        /workspace/pkg/apiserver/apiserver.go:192 +0x7c fp=0xc001e3f110 sp=0xc001e3f018 pc=0x254eb3c
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001241590, 0xc001241500, 0xc00085f1f0)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/filter.go:19 +0x66 fp=0xc001e3f138 sp=0xc001e3f110 pc=0x12d9846
kubesphere.io/kubesphere/pkg/apiserver.logRequestAndResponse(0xc001241500, 0xc00085f1f0, 0xc001241590)
        /workspace/pkg/apiserver/apiserver.go:605 +0x85 fp=0xc001e3f3b8 sp=0xc001e3f138 pc=0x2555385
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001241590, 0xc001241500, 0xc00085f1f0)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/filter.go:19 +0x66 fp=0xc001e3f3e0 sp=0xc001e3f3b8 pc=0x12d9846
github.com/emicklei/go-restful.(*Container).dispatch(0xc0009d1a70, 0x3a06b08, 0xc0008be000, 0xc000930500)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/container.go:291 +0x473 fp=0xc001e3f548 sp=0xc001e3f3e0 pc=0x12d56f3
github.com/emicklei/go-restful.(*Container).dispatch-fm(0x3a06b08, 0xc0008be000, 0xc000930500)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/container.go:208 +0x51 fp=0xc001e3f578 sp=0xc001e3f548 pc=0x12e46b1
net/http.HandlerFunc.ServeHTTP(0xc000b61f40, 0x3a06b08, 0xc0008be000, 0xc000930500)
        /usr/local/go/src/net/http/server.go:2069 +0x44 fp=0xc001e3f5a0 sp=0xc001e3f578 pc=0x7fa0e4
net/http.(*ServeMux).ServeHTTP(0xc000b7f740, 0x3a06b08, 0xc0008be000, 0xc000930500)
        /usr/local/go/src/net/http/server.go:2448 +0x1ad fp=0xc001e3f600 sp=0xc001e3f5a0 pc=0x7fbf6d
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc0009d1a70, 0x3a06b08, 0xc0008be000, 0xc000930500)
        /go/pkg/mod/github.com/emicklei/go-restful@v2.14.3+incompatible/container.go:311 +0x299 fp=0xc001e3f680 sp=0xc001e3f600 pc=0x12d6159
kubesphere.io/kubesphere/pkg/apiserver/filters.WithKubeAPIServer.func1(0x3a06b08, 0xc0008be000, 0xc000930500)
        /workspace/pkg/apiserver/filters/kubeapiserver.go:62 +0x382 fp=0xc001e3f7c8 sp=0xc001e3f680 pc=0x21fa802
net/http.HandlerFunc.ServeHTTP(0xc000ea1b40, 0x3a06b08, 0xc0008be000, 0xc000930500)
        /usr/local/go/src/net/http/server.go:2069 +0x44 fp=0xc001e3f7f0 sp=0xc001e3f7c8 pc=0x7fa0e4
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x3a06b08, 0xc0008be000, 0xc000930500)
        /workspace/pkg/apiserver/filters/authorization.go:52 +0x388 fp=0xc001e3f8e8 sp=0xc001e3f7f0 pc=0x21fa228
net/http.HandlerFunc.ServeHTTP(0xc000ea1bc0, 0x3a06b08, 0xc0008be000, 0xc000930500)
        /usr/local/go/src/net/http/server.go:2069 +0x44 fp=0xc001e3f910 sp=0xc001e3f8e8 pc=0x7fa0e4
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x3a06b08, 0xc0008be000, 0xc000930500)
        /workspace/pkg/apiserver/filters/authentication.go:70 +0x5f8 fp=0xc001e3fa40 sp=0xc001e3f910 pc=0x21f9c78
net/http.HandlerFunc.ServeHTTP(0xc000ea1c40, 0x3a06b08, 0xc0008be000, 0xc000930400)
        /usr/local/go/src/net/http/server.go:2069 +0x44 fp=0xc001e3fa68 sp=0xc001e3fa40 pc=0x7fa0e4
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x3a06b08, 0xc0008be000, 0xc000930300)
        /workspace/pkg/apiserver/filters/requestinfo.go:69 +0x3d1 fp=0xc001e3fb48 sp=0xc001e3fa68 pc=0x21fad31
net/http.HandlerFunc.ServeHTTP(0xc000d05200, 0x3a06b08, 0xc0008be000, 0xc000930300)
        /usr/local/go/src/net/http/server.go:2069 +0x44 fp=0xc001e3fb70 sp=0xc001e3fb48 pc=0x7fa0e4
net/http.serverHandler.ServeHTTP(0xc00067a460, 0x3a06b08, 0xc0008be000, 0xc000930300)
        /usr/local/go/src/net/http/server.go:2887 +0xa3 fp=0xc001e3fba0 sp=0xc001e3fb70 pc=0x7fd6a3
net/http.(*conn).serve(0xc000cc4140, 0x3a0d788, 0xc002cec1c0)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd fp=0xc001e3ffc8 sp=0xc001e3fba0 pc=0x7f8bcd
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001e3ffd0 sp=0xc001e3ffc8 pc=0x46eae1
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Versions Used**
KubeSphere: v3.1.1

**Environment**

Linux debian 5.10.0-8-amd64, single node, 4cpu/8g

**How To Reproduce**
Sorry, I can't reproduce. This happened when os at high load, and some pods are going to be evicted.

**Comment by dkeven** [comment]
IMO, this might be an issue related with the `sharedInformer` used by all the `ResourceGetter`s.

The K8s `runtime.Object`s retrieved from `informer...List/Get()` are stored in a cache managed by the informer, which updates the objects continuously to mirror the changes made by the `kube-apiserver`.

When `handler` writes the objects to the response, the objects will be `marshal`ed to json, which effectively executes a map reading op if any field is of type `map`.

Theoretically, when `ks-apiserver` is under high load, and the K8s objects are altered, either frequent or concurrent enough, there's a chance of cocurrent map reading and writing.

@xushuxun Can you be more specific about which resource caused this panic? And what do you mean by 

> ks-apiserver may crash

If the guessing above is right, there'll be only one panicking goroutine per request, rather than the whole `ks-apiserver` crashing.

Also
/cc @zryfish @wansir 
Please correct me if I'm wrong.

**Comment by dkeven** [comment]
I think a `DeepCopy()` is necessary every time an object is retrieved from the `sharedInformer`'s `cache`, not only to avoid this kind of panics, but also because we should never modify the objects inside the reflected `cache`.

refer:
https://kubesphere.com.cn/forum/d/6466-fatal-error-concurrent-map-writes

**Comment by zryfish** [comment]
> I think a `DeepCopy()` is necessary every time an object is retrieved from the `sharedInformer`'s `cache`, not only to avoid this kind of panics, but also because we should never modify the objects inside the reflected `cache`.
> 
> refer: https://kubesphere.com.cn/forum/d/6466-fatal-error-concurrent-map-writes

Could you file a PR to address your idea?

**Comment by dkeven** [comment]
> 

Okay, I'll file a PR against the `node` module.

**Comment by dkeven** [comment]
I've found a way to greatly improve the possibility of reproducing this issue:

1. go to KS console → Storage → Volumes (or any other resource listing API, as long as it does writing to maps of any shared objects)
2. hit F12 to open the debug console
3. go to network → XHR
4. hit the refresh button above the resource list on the KS console
5. copy the captured request as cURL(bash)
6. open two terminals, and **simultaneously** executing the request many times, like beblow:

```bash
for i in {1..500}
do
<paste the request command here>
done
```

when `Service Unavailable` appears, that means the ks-apiserver has crashed.

Now, if you execute `kukubectl -n kubesphere-system logs -n kubesphere-system ks-apiserver-5847dc5797-4bp4m -p`

The log will look like this, indicating a concurrent write of map has caused the process to panic:
```
fatal error: concurrent map writes

goroutine 3937 [running]:
runtime.throw(0x3b7396a, 0x15)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0045ead08 sp=0xc0045eacd8 pc=0x4380d2
runtime.mapassign_faststr(0x35989e0, 0xc0015b2870, 0x3b71262, 0x14, 0xc0013e7a88)
        /usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc0045ead70 sp=0xc0045ead08 pc=0x4146d1
kubesphere.io/kubesphere/pkg/models/resources/v1alpha3/persistentvolumeclaim.(*persistentVolumeClaimGetter).annotatePVC(0xc000a6af80, 0xc0015c06e0)
        /workspace/pkg/models/resources/v1alpha3/persistentvolumeclaim/persistentvolumeclaim.go:108 +0x12f fp=0xc0045eadd8 sp=0xc0045ead70 pc=0x276336f
```

This is a simple simulation of the bug, in other cases, two different API processing might also read/write a map at the same time, causing the same error.
