### ISSUE TITLE
ks-controller-manager crash

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#4601]
**Describe the Bug**
ks-controller-manager continually crash with the following log.

```
 W0110 01:53:34.511377       1 controllers.go:163] ks-controller-manager starts without ldap provided, it will not sync user into ldap
 panic: assignment to entry in nil map
 goroutine 1 [running]:
 kubesphere.io/kubesphere/pkg/controller/helm.(*Reconciler).defaultConfiguration(...)
 	/workspace/pkg/controller/helm/helm_controller.go:83
 kubesphere.io/kubesphere/pkg/controller/helm.(*Reconciler).SetupWithManager(0xc000411420, 0x3354da0, 0xc000c08000, 0x7ff22a59d5b8, 0x8)
 	/workspace/pkg/controller/helm/helm_controller.go:62 +0x7cf
 kubesphere.io/kubesphere/cmd/controller-manager/app.addControllerWithSetup(0x3354da0, 0xc000c08000, 0x2e99160, 0x4, 0x32b8260, 0xc000411420)
 	/workspace/cmd/controller-manager/app/controllers.go:528 +0x55
 kubesphere.io/kubesphere/cmd/controller-manager/app.addAllControllers(0x3354da0, 0xc000c08000, 0x3344a98, 0xc0001a8000, 0x333ad68, 0xc000597260, 0xc0006eebe0, 0xc000d0e8a0, 0x0, 0x2eb494e)
 	/workspace/cmd/controller-manager/app/controllers.go:266 +0x3756
```
**Versions Used**
KubeSphere: master build
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by RolandMa1986** [comment]
/kind bug
@chaunceyjiang would you like to take a look at this issue?

**Comment by chaunceyjiang** [comment]
> 

ok
