### ISSUE TITLE
Failed to fetch GPU kinds

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#4825]
**Describe the Bug**

Failed to fetch GPU kinds, caused by ks-apiserver NPE.

Error logs:

```
FetchError: request to http://ks-apiserver/kapis/config.kubesphere.io/v1alpha2/configs/gpu/kinds failed, reason: socket hang up
    at ClientRequest.<anonymous> (/opt/kubesphere/console/server/server.js:49572:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketOnEnd (_http_client.js:458:9)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

```
2022/04/26 07:44:14 http: panic serving 10.233.116.24:43170: runtime error: invalid memory address or nil pointer dereference
goroutine 11500 [running]:
net/http.(*conn).serve.func1(0xc008a314a0)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x35eb3a0, 0x5d68090)
	/usr/local/go/src/runtime/panic.go:971 +0x499
kubesphere.io/kubesphere/pkg/kapis/config/v1alpha2.AddToContainer.func3(0xc0069b4d50, 0xc001224e00)
	/workspace/pkg/kapis/config/v1alpha2/register.go:51 +0x2c
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0069b4de0, 0xc0069b4d50, 0xc001224e00)
	/workspace/vendor/github.com/emicklei/go-restful/filter.go:21 +0x8c
kubesphere.io/kubesphere/pkg/apiserver.monitorRequest(0xc0069b4d50, 0xc001224e00, 0xc0069b4de0)
	/workspace/pkg/apiserver/apiserver.go:189 +0x7c
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0069b4de0, 0xc0069b4d50, 0xc001224e00)
	/workspace/vendor/github.com/emicklei/go-restful/filter.go:19 +0x66
kubesphere.io/kubesphere/pkg/apiserver.logRequestAndResponse(0xc0069b4d50, 0xc001224e00, 0xc0069b4de0)
	/workspace/pkg/apiserver/apiserver.go:602 +0x85
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0069b4de0, 0xc0069b4d50, 0xc001224e00)
	/workspace/vendor/github.com/emicklei/go-restful/filter.go:19 +0x66
github.com/emicklei/go-restful.(*Container).dispatch(0xc000b72000, 0x41c4d08, 0xc0069b4cf0, 0xc008b91a00)
	/workspace/vendor/github.com/emicklei/go-restful/container.go:291 +0x473
net/http.HandlerFunc.ServeHTTP(0xc0006082e0, 0x41c4d08, 0xc0069b4cf0, 0xc008b91a00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000b60040, 0x41c4d08, 0xc0069b4cf0, 0xc008b91a00)
	/usr/local/go/src/net/http/server.go:2448 +0x1ad
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc000b72000, 0x41c4d08, 0xc0069b4cf0, 0xc008b91a00)
	/workspace/vendor/github.com/emicklei/go-restful/container.go:311 +0x299
kubesphere.io/kubesphere/pkg/apiserver/filters.WithKubeAPIServer.func1(0x41c4d08, 0xc0069b4cf0, 0xc008b91a00)
	/workspace/pkg/apiserver/filters/kubeapiserver.go:62 +0x382
net/http.HandlerFunc.ServeHTTP(0xc0001c95c0, 0x41c4d08, 0xc0069b4cf0, 0xc008b91a00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuditing.func1(0x41c5308, 0xc003391260, 0xc008b91a00)
	/workspace/pkg/apiserver/filters/auditing.go:56 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc000f78ba0, 0x41c5308, 0xc003391260, 0xc008b91a00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x41c5308, 0xc003391260, 0xc008b91a00)
	/workspace/pkg/apiserver/filters/authorization.go:52 +0x388
net/http.HandlerFunc.ServeHTTP(0xc0001c9680, 0x41c5308, 0xc003391260, 0xc008b91a00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithMultipleClusterDispatcher.func1(0x41c5308, 0xc003391260, 0xc008b91a00)
	/workspace/pkg/apiserver/filters/dispatch.go:45 +0xe4
net/http.HandlerFunc.ServeHTTP(0xc000f79410, 0x41c5308, 0xc003391260, 0xc008b91a00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x41c5308, 0xc003391260, 0xc008b91a00)
	/workspace/pkg/apiserver/filters/authentication.go:70 +0x5f8
net/http.HandlerFunc.ServeHTTP(0xc0001c9f00, 0x41c5308, 0xc003391260, 0xc004225200)
	/usr/local/go/src/net/http/server.go:2069 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x41c5308, 0xc003391260, 0xc004224c00)
	/workspace/pkg/apiserver/filters/requestinfo.go:69 +0x3d1
net/http.HandlerFunc.ServeHTTP(0xc000f79b30, 0x41c5308, 0xc003391260, 0xc004224c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000b9e2a0, 0x41c5308, 0xc003391260, 0xc004224c00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc008a314a0, 0x41ce1c0, 0xc007636d80)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Versions Used**
KubeSphere: v3.3.0-alpha.1.2+7d9563dca1e5d4

/kind bug
/priority high

**Comment by benjaminhuo** [comment]
@wenchajun Would you help to take a look at this issue?

**Comment by zheng1** [comment]
@wenchajun Anything update?

**Comment by wenchajun** [comment]
> @wenchajun Anything update?

This may be a configuration issue.

**Comment by wansir** [comment]
I think the exception should be caught, panic still exists with an unexpected API call.
