### ISSUE TITLE
success install but login error, msg is `getaddrinfo EAI_AGAIN ks-apiserver`

### ISSUE THREAD

**Issue by MissYBYue** [kubesphere/kubesphere#4858]
login fail, `request to http://ks-apiserver/oauth/token failed, reason: getaddrinfo EAI_AGAIN ks-apiserver`
![image](https://user-images.githubusercontent.com/48619456/167281269-65a158be-bc2d-4724-aa7c-ba018bc8c340.png)

**Versions Used**
KubeSphere: v3.2.1
Kubernetes: v1.22.1
kk version: 2.0.0

**Environment**
 CentOS 7.8 / 1 masters:  4cpu/8g; 2 nodes:  4cpu/8g

**kk.config**
  - {name: k8s-master, address: 10.11.1.166, internalAddress: 192.168.0.16, user: root, password: "root12300."}
  - {name: k8s-node-1, address: 10.11.1.20, internalAddress: 192.168.0.127, user: root, password: "root12300."}
  - {name: k8s-node-2, address: 10.11.3.230, internalAddress: 192.168.0.131, user: root, password: "root12300."}

```bash
[root@k8s-master ~]# kubectl logs ks-apiserver-85f547dd9-fqkzc -n kubesphere-system
W0508 02:52:04.819138       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0508 02:52:04.827795       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0508 02:52:04.852483       1 metricsserver.go:238] Metrics API not available.
W0508 02:52:04.852556       1 options.go:183] ks-apiserver starts without redis provided, it will use in memory cache. This may cause inconsistencies when running ks-apiserver with multiple replicas.
I0508 02:52:05.671277       1 interface.go:60] start helm repo informer
I0508 02:52:05.729956       1 apiserver.go:356] Start cache objects
I0508 02:52:06.894600       1 apiserver.go:562] Finished caching objects
I0508 02:52:06.894741       1 apiserver.go:278] Start listening on :9090

[root@k8s-master ~]# kubectl logs ks-console-65f4d44d88-fjhwf -n kubesphere-system

> kubesphere-console@3.0.0 serve /opt/kubesphere/console
> NODE_ENV=production node server/server.js

Dashboard app running at port 8000
  <-- POST /login 2022/05/07T13:23:40.365
FetchError: request to http://ks-apiserver/oauth/token failed, reason: getaddrinfo EAI_AGAIN ks-apiserver
    at ClientRequest.<anonymous> (/opt/kubesphere/console/server/server.js:47991:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
  --> POST /login 200 5,082ms 128b 2022/05/07T13:23:45.445
  <-- POST /login 2022/05/07T13:24:12.657
FetchError: request to http://ks-apiserver/oauth/token failed, reason: getaddrinfo EAI_AGAIN ks-apiserver
    at ClientRequest.<anonymous> (/opt/kubesphere/console/server/server.js:47991:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}

[root@k8s-master ~]# kubectl logs ks-controller-manager-6bbb6f4544-6ms9c -n kubesphere-system | grep error
E0508 02:51:40.964180       1 controller.go:304] controller/user-controller "msg"="Reconciler error" "error"="certificatesigningrequests.certificates.k8s.io \"admin-csr-1651978300\" already exists" "name"="admin" "namespace"="" "reconciler group"="iam.kubesphere.io" "reconciler kind"="User"
```

**Comment by MissYBYue** [comment]
restart host .all is ok...
