### ISSUE TITLE
ks-apiserver CrashLoopBackOff,How to turn off built-in monitoring completely?

### ISSUE THREAD

**Issue by Changego** [kubesphere/kubesphere#4926]
Hi
now,ks-apiserver CrashLoopBackOff 

How to turn off built-in monitoring completely?
I just want to use Devops, K8S management, logs, events
```shell
E0531 18:14:08.678281       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:128: Failed to watch *v2beta1.Receiver: failed to list *v2beta1.Receiver: conversion webhook for notification.kubesphere.io/v2beta2, Kind=Receiver failed: Post "https://notification-manager-webhook.kubesphere-monitoring-system.svc:443/convert?timeout=30s": service "notification-manager-webhook" not found
E0531 18:14:19.017114       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:128: Failed to watch *v2beta1.Config: failed to list *v2beta1.Config: conversion webhook for notification.kubesphere.io/v2beta2, Kind=Config failed: Post "https://notification-manager-webhook.kubesphere-monitoring-system.svc:443/convert?timeout=30s": service "notification-manager-webhook" not found
I0531 18:14:24.983735       1 apiserver.go:562] Finished caching objects
I0531 18:14:24.983833       1 apiserver.go:278] Start listening on :9090
E0531 18:14:24.984055       1 runtime.go:78] Observed a panic: "close of closed channel" (close of closed channel)
goroutine 1199 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x35cb680, 0x40e4bb0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x35cb680, 0x40e4bb0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/cache.(*processorListener).pop(0xc000e9bd00)
        /workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:752 +0x2a5
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0001fdb10, 0xc004e757b0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
panic: close of closed channel [recovered]
        panic: close of closed channel
```

**Comment by xyz-li** [comment]
It is impossible to disable the built-in monitoring function.


> ```shell
> E0531 18:14:08.678281       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:128: Failed to watch *v2beta1.Receiver: failed to list *v2beta1.Receiver: conversion webhook for notification.kubesphere.io/v2beta2, Kind=Receiver failed: Post "https://notification-manager-webhook.kubesphere-monitoring-system.svc:443/convert?timeout=30s": service "notification-manager-webhook" not found
> ```
Does the service notification-manager-webhook exist in the namespace kubesphere-monitoring-system?
If it does not exist, can you provide the log of ks-installer?

**Comment by Changego** [comment]
I know， that namespace kubesphere- Monitoring - System is manually deleted
As long as kS-Apiserver can start using K8S management, Devops,logs, events. The monitoring and alarm functions are not required.

**Comment by xyz-li** [comment]
You need to restart the ks-installer pod to re-create the ns `kubesphere-monitoring-system`.
And it is `IMPOSSIBLE` to disable the built-in monitoring function.
