### ISSUE TITLE
Multi-Node模式安装失败，Download items任务时报错并终止

### ISSUE THREAD

**Issue by bowenliang123** [kubesphere/kubesphere#595]
尝试在以1Master+2Node以Multi-Node模式进行部署
在Master节点，以在线版安装包执行 `sudo ./install.sh`后，在以下环节出错并终止。

```
（前面正常）

TASK [download : container_download | Create dest directory for saved/loaded container images] ***********************
Monday 22 July 2019  16:19:23 +0800 (0:00:00.406)       0:01:01.224 *********** 
ok: [node1]
ok: [node2]

TASK [download : container_download | create local directory for saved/loaded container images] **********************
Monday 22 July 2019  16:19:24 +0800 (0:00:00.249)       0:01:01.474 *********** 

TASK [download : Download items] *************************************************************************************
Monday 22 July 2019  16:19:24 +0800 (0:00:00.045)       0:01:01.519 *********** 
fatal: [node2]: FAILED! => {"reason": "'delegate_to' is not a valid attribute for a TaskInclude\n\nThe error appears to be in '/home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_container.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: container_download | Make download decision if pull is required by tag or sha256\n  ^ here\n"}
fatal: [node1]: FAILED! => {"reason": "'delegate_to' is not a valid attribute for a TaskInclude\n\nThe error appears to be in '/home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_container.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: container_download | Make download decision if pull is required by tag or sha256\n  ^ here\n"}
included: /home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_file.yml for node2, node1
fatal: [node2]: FAILED! => {"reason": "'delegate_to' is not a valid attribute for a TaskInclude\n\nThe error appears to be in '/home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_container.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: container_download | Make download decision if pull is required by tag or sha256\n  ^ here\n"}
fatal: [node1]: FAILED! => {"reason": "'delegate_to' is not a valid attribute for a TaskInclude\n\nThe error appears to be in '/home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_container.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: container_download | Make download decision if pull is required by tag or sha256\n  ^ here\n"}
fatal: [node2]: FAILED! => {"reason": "'delegate_to' is not a valid attribute for a TaskInclude\n\nThe error appears to be in '/home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_container.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: container_download | Make download decision if pull is required by tag or sha256\n  ^ here\n"}
fatal: [node1]: FAILED! => {"reason": "'delegate_to' is not a valid attribute for a TaskInclude\n\nThe error appears to be in '/home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_container.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: container_download | Make download decision if pull is required by tag or sha256\n  ^ here\n"}
included: /home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_file.yml for node2, node1
included: /home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_file.yml for node2, node1

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
master                     : ok=30   changed=0    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0   
node1                      : ok=106  changed=2    unreachable=0    failed=10   skipped=112  rescued=0    ignored=0   
node2                      : ok=94   changed=1    unreachable=0    failed=10   skipped=108  rescued=0    ignored=0   

Monday 22 July 2019  16:19:25 +0800 (0:00:01.262)       0:01:02.782 *********** 
=============================================================================== 
kubernetes/preinstall : Update package management cache (YUM) ------------------------------------------------- 9.34s
gather facts from all instances ------------------------------------------------------------------------------- 4.56s
kubernetes/preinstall : Install packages requirements --------------------------------------------------------- 2.93s
download : Download items ------------------------------------------------------------------------------------- 1.26s
download : Download items ------------------------------------------------------------------------------------- 1.13s
download : Sync container ------------------------------------------------------------------------------------- 1.07s
download : Download items ------------------------------------------------------------------------------------- 1.05s
download : Sync container ------------------------------------------------------------------------------------- 1.04s
bootstrap-os : Check python-pip package ----------------------------------------------------------------------- 1.03s
bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS and Tumbleweed) -------------------- 1.00s
container-engine/docker : docker login ------------------------------------------------------------------------ 1.00s
kubernetes/preinstall : Create kubernetes directories --------------------------------------------------------- 0.96s
bootstrap-os : Gather nodes hostnames ------------------------------------------------------------------------- 0.94s
bootstrap-os : Install pip for bootstrap ---------------------------------------------------------------------- 0.88s
bootstrap-os : Install libselinux-python and yum-utils for bootstrap ------------------------------------------ 0.86s
container-engine/docker : ensure service is started if docker packages are already present -------------------- 0.78s
kubernetes/preinstall : Hosts | populate inventory into hosts file -------------------------------------------- 0.72s
kubernetes/preinstall : Set selinux policy -------------------------------------------------------------------- 0.71s
bootstrap-os : Install epel-release for bootstrap ------------------------------------------------------------- 0.66s
kubernetes/preinstall : Create cni directories ---------------------------------------------------------------- 0.62s
failed!
```

请问各位，有没有什么头绪可以帮忙解决？

**Comment by bowenliang123** [comment]
附上报错中提到的/home/develop/kubesphere/kubesphere-all-advanced-2.0.2/k8s/roles/download/tasks/download_container.yml

**Comment by lilinlinlin** [comment]
hosts.ini文件发下看下

**Comment by bowenliang123** [comment]
`conf/hosts.ini ` 如下

```

[all]
master ansible_connection=local  ip=172.16.134.123
node1  ansible_host=172.16.134.122  ip=172.16.134.122  ansible_ssh_pass=password
node2  ansible_host=172.16.134.121  ip=172.16.134.121  ansible_ssh_pass=password

[kube-master]
master

[kube-node]
master
node1
node2

[etcd]
master

[k8s-cluster:children]
kube-node
kube-master

```

**Comment by bowenliang123** [comment]
kubesphere在线版安装包对ansible有要求吗，一开始反复提示ansible-playbook命令不存在，我在手动安装yum install ansible 然后才真正开始了流程。

我的系统是阿里云机器，CentOS版本7.6，当前ansible版本为2.8.1

**Comment by bowenliang123** [comment]
如果没有手动安装ansible，执行在线版安装包会有如下错误：


```
################################################
         KubeSphere Installer Menu
################################################
*   1) All-in-one
*   2) Multi-node
*   3) Quit
################################################
https://kubesphere.io/               2019-07-22
################################################
Please input an option: 2
2
Have you configured storage parameters in conf/vars.yml yet?  (yes/no) yes
Package epel-release-7-11.noarch already installed and latest version
Nothing to do
Package python2-pip-8.1.2-8.el7.noarch already installed and latest version
Package python-netaddr-0.7.5-9.el7.noarch already installed and latest version
Package sshpass-1.06-2.el7.x86_64 already installed and latest version
Nothing to do
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting ansible==2.7.6 (from -r os/requirements.txt (line 1))
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/db/3e/04d67f7798432542dcf0258b59634f4f60f1f9ba9505cc71d69af88673d6/ansible-2.7.6.tar.gz (11.8MB)
     |████████████████████████████████| 11.8MB 18.7MB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-voTIRk/ansible/setup.py", line 315, in <module>
        main()
      File "/tmp/pip-install-voTIRk/ansible/setup.py", line 310, in main
        setup(**setup_params)
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2341, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-voTIRk/ansible/
./multi-node.sh: line 41: ansible-playbook: command not found
failed!
```

**Comment by lilinlinlin** [comment]
脚本中会自动安装ansible

**Comment by bowenliang123** [comment]
对按道理是应该自动安装吧。但从错误提示来看是脚本在安装ansible时候似乎出现了问题

**Comment by bowenliang123** [comment]
https://blog.csdn.net/yanghx9013/article/details/79496527

**Comment by lilinlinlin** [comment]
把ansible  remove吧，yum remove ansible -y，然后再跑下安装

**Comment by lilinlinlin** [comment]
对ansible版本有一定要求

**Comment by bowenliang123** [comment]
`pip install --upgrade setuptools==30.1.0` 暂时用这个命令，让通过脚本顺利安装ansible了，有机会的话尽量考虑在脚本兼容一下。

这个问题就先关闭了。然后谢谢你的帮助。
我又遇到新的问题，考虑另起issue了。
