### ISSUE TITLE
After All-In-One Installation Successfully, view ip:30880 from browser failed

### ISSUE THREAD

**Issue by ljwayne** [kubesphere/kubesphere#6043]
**Environment: OS & Hardware Information**

Ubuntu 22.04.3 LTS
Docker version 25.0.2, build 29cf629
K8s：v1.22.12

**Error logs or message (Attach logs or screenshot)**
every pods and service status OK, telnet ip 30880 is OK, but curl ip:30880 cost 5-6minutes so that view it from browser failed
![image](https://github.com/kubesphere/kubesphere/assets/48937411/94307013-4ff7-4265-bf89-d7b5d213c55a)
![image](https://github.com/kubesphere/kubesphere/assets/48937411/c30d014d-a2f9-4d56-9d9b-f8c4e76ccbf2)
![image](https://github.com/kubesphere/kubesphere/assets/48937411/1eb8832c-813c-4830-8372-54b6908e391c)

**Installer Version**

> e.g. v2.1.0, v2.1.1, v3.0.0
v3.4.0

**Comment by include** [comment]
Same problem here. (more modern versions) but the same behavour. Any hint to debug?

**Comment by pixiake** [comment]
![image](https://github.com/kubesphere/kubesphere/assets/22290449/6680b804-5c82-4e17-bffe-999b10a277da)

I think you can first check the connectivity between pods and nodePort.
curl {podIP}:8000
curl {svc ClusterIP}:80
curl {nodeIP}:30880

Its should have the same output.

**Comment by bbscncom** [comment]
same problem here
./kk create cluster --with-kubernetes v1.22.12 --with-kubesphere v3.4.1
all is running,but 30880 can't connect
80 30880 8000 ，curl  not response

root@debian:/home/bbs# kubectl -n kubesphere-system logs -l app=ks-console --tail=30
    at async /opt/kubesphere/console/server/server.js:40154:7
    at async logger (/opt/kubesphere/console/server/server.js:37098:7)
    at async /opt/kubesphere/console/server/server.js:31861:26
    at async /opt/kubesphere/console/server/server.js:31861:26
    at async /opt/kubesphere/console/server/server.js:31861:26
    at async /opt/kubesphere/console/server/server.js:31655:5
FetchError: request to http://ks-apiserver/kapis/version failed, reason: connect ETIMEDOUT 10.233.48.238:80
    at ClientRequest.<anonymous> (/opt/kubesphere/console/server/server.js:19515:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:23007:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:6992:14)
    at renderView (/opt/kubesphere/console/server/server.js:72141:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /opt/kubesphere/console/server/server.js:40154:7
    at async logger (/opt/kubesphere/console/server/server.js:37098:7)
    at async /opt/kubesphere/console/server/server.js:31861:26
    at async /opt/kubesphere/console/server/server.js:31861:26
  --> GET / 302 131s 43b 2024/04/22T20:22:30.726
    at async /opt/kubesphere/console/server/server.js:31861:26
    at async /opt/kubesphere/console/server/server.js:31655:5


10.233.48.238:80  is api-server



root@debian:/home/bbs# kubectl -n kubesphere-system logs -l app=ks-apiserver --tail=30
W0422 18:26:42.424901       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0422 18:26:42.426433       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0422 18:26:42.436462       1 metricsserver.go:238] Metrics API not available.
W0422 18:26:42.436506       1 cache.go:64] In-memory cache will be used, this may cause data inconsistencies when running with multiple replicas.
I0422 18:26:42.436533       1 interface.go:50] start helm repo informer
I0422 18:26:42.985296       1 apiserver.go:428] Start cache objects
W0422 18:26:42.999897       1 apiserver.go:405] group version autoscaling/v2 not exists in the cluster
I0422 18:26:44.042699       1 apiserver.go:619] Finished caching objects
I0422 18:26:44.042752       1 apiserver.go:297] Start listening on :9090

**Comment by bbscncom** [comment]
i resolve my problem.
i change vmware VMnet8(nat) to VMnet1,now i can view login path.
i dont know what happen ,info maybe helpful is that i set static ip 192.168.155.6 for ens33 in interfaces file.   
Maybe i use VMnet8 and change static to dhcp ，then all will perfect？

**Comment by huelsgp27** [comment]
same problem.
