### ISSUE TITLE
V3.4.1 邮件功能报错,

### ISSUE THREAD

**Issue by Awaion** [kubesphere/kubesphere#6113]
java.lang.NoSuchMethodError: 'jenkins.plugins.mailer.tasks.MimeMessageBuilder jenkins.plugins.mailer.tasks.MimeMessageBuilder.addRecipients(java.lang.String, javax.mail.Message$RecipientType)'
	at org.jenkinsci.plugins.workflow.steps.MailStep$MailStepExecution.buildMimeMessage(MailStep.java:166)
	at org.jenkinsci.plugins.workflow.steps.MailStep$MailStepExecution.run(MailStep.java:141)
	at org.jenkinsci.plugins.workflow.steps.MailStep$MailStepExecution.run(MailStep.java:128)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

有开发者指出 javax.mail.Message$RecipientType instead of jakarta.mail.Message$RecipientType.

https://stackoverflow.com/questions/73476360/the-jenkins-pipeline-send-email-error-with-java-lang-nosuchmethoderror

**Comment by Awaion** [comment]
是鲁班版本,搞错了
