### ISSUE TITLE
openpitrix-app-db-ctrl-job和openpitrix-repo-db-ctrl-job执行失败

### ISSUE THREAD

**Issue by major-jay** [kubesphere/kubesphere#685]
**问题描述**
openpitrix-app-db-ctrl-job和openpitrix-repo-db-ctrl-job执行失败
**安装环境的硬件配置**
3台4C16G组成的本地节点
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
物理机
**错误信息或截图**
Current version of schema `app`: 0.7
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Schema `app` contains a failed migration to version 0.7 !
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:227)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:53)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:163)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:160)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:80)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:150)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:160)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:138)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:947)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:910)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1238)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:910)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)
**Installer版本**
2.0.2

我在云主机执行是成功的，在本地执行报错，我不知道需要修改什么

**Comment by zheng1** [comment]
请问这个是在已有的环境升级还是全新安装的？使用的是什么存储？

**Comment by JDalready** [comment]
> 请问这个是在已有的环境升级还是全新安装的？使用的是什么存储？

删除pv  并重装环境就好了  应该是db初始化问题  不能再次初始化  我很疑惑
