### ISSUE TITLE
centos7.5 安装2.0.2失败

### ISSUE THREAD

**Issue by wu997134245** [kubesphere/kubesphere#812]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
centos7.5 安装2.0.2失败
**安装环境的硬件配置**
8核16G，200G硬盘

**错误信息或截图**

TASK [download : Check the local digest sha256 corresponds to the given image tag] **************************************************************************************************************************************************************
Friday 27 September 2019  03:10:26 -0400 (0:00:00.147)       0:11:57.079 ****** 

TASK [download : container_download | Download containers if pull is required or told to always pull (delegate)] ********************************************************************************************************************************
Friday 27 September 2019  03:10:26 -0400 (0:00:00.127)       0:11:57.207 ****** 

TASK [download : container_download | Download containers if pull is required or told to always pull (all nodes)] *******************************************************************************************************************************
Friday 27 September 2019  03:10:26 -0400 (0:00:00.083)       0:11:57.291 ****** 
FAILED - RETRYING: container_download | Download containers if pull is required or told to always pull (all nodes) (4 retries left).
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 875, in emit
  File "/usr/lib64/python2.7/logging/__init__.py", line 835, in flush
IOError: [Errno 5] Input/output error
Logged from file display.py, line 174
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 5] Input/output error: '/usr/lib/python2.7/site-packages/ansible/modules/commands/command.py'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 875, in emit
  File "/usr/lib64/python2.7/logging/__init__.py", line 835, in flush
IOError: [Errno 5] Input/output error
Logged from file display.py, line 172
fatal: [ks-allinone]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 875, in emit
  File "/usr/lib64/python2.7/logging/__init__.py", line 835, in flush
IOError: [Errno 5] Input/output error
Logged from file display.py, line 172

PLAY RECAP **************************************************************************************************************************************************************************************************************************************
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 875, in emit
  File "/usr/lib64/python2.7/logging/__init__.py", line 835, in flush
IOError: [Errno 5] Input/output error
Logged from file display.py, line 174
ks-allinone                : ok=116  changed=20   unreachable=0    failed=1   
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 875, in emit
  File "/usr/lib64/python2.7/logging/__init__.py", line 835, in flush
IOError: [Errno 5] Input/output error
Logged from file display.py, line 174
Friday 27 September 2019  07:10:48 +0000 (0:00:22.633)       0:12:19.925 ****** 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 875, in emit
  File "/usr/lib64/python2.7/logging/__init__.py", line 835, in flush
IOError: [Errno 5] Input/output error
Logged from file display.py, line 174

**Installer版本**
2.0.2

**Comment by rayzhou2017** [comment]
到https://github.com/kubesphere/ks-installer/issues找找答案
